### ISSUE TITLE
Als gemeente wil ik de gegevens van een ingeschreven persoon kunnen raadplegen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#10]
...zodat ik deze gegevens kan gebruiken.

**Acceptatiecriteria**
- [x] De persoon waarvan gegevens worden geraadpleegd kan worden geselecteerd op basis van het burgerservicenummer
- [x] Het is mogelijk de verblijfsplaatshistorie van de persoon te raadplegen
- [x] Het is mogelijk de partnerhistorie van de persoon te raadplegen
- [x] Het is mogelijk de verblijfstitelhistorie van de persoon te raadplegen

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Hoe wordt dit geïmplementeerd in de API? Willen we bijvoorbeeld verblijfplaatshistorie krijgen binnen een aanroep van /ingeschrevennatuurlijkpersonen/{burgerservicenummer}?
Of willen we verblijfplaatshistorie krijgen via een aanroep van /ingeschrevennatuurlijkpersonen/{burgerservicenummer}/verblijfplaatsen?

**Comment by CathyDingemanse** [comment]
> ...zodat ik deze gegevens kan gebruiken.
> 
> **Acceptatiecriteria**
> 
> * [ ]  De persoon waarvan gegevens worden geraadpleegd kan worden geselecteerd op basis van het burgerservicenummer
> * [ ]  Het is mogelijk de verblijfsplaatshistorie van de persoon te raadplegen
> * [ ]  Het is mogelijk de partnerhistorie van de persoon te raadplegen
Verblijfstitelhistorie ontbreekt!
> 
> **Definition of done**
> 
> * [ ]  functionele specificatie
> * [ ]  Open API specificatie
> * [ ]  gegenereerde code
> * [ ]  testgevallen

**Comment by fsamwel** [comment]
Ik heb acceptatie criterium "Het is mogelijk de verblijfstitelhistorie van de persoon te raadplegen" toegevoegd aan de beschrijving.

**Comment by JohanBoer** [comment]
ik heb nu de volgende endpoints opgenomen in de API-specificatie :
- /ingeschrevennatuurlijkpersonen/{burgerservicenummer}
- /verblijfsplaatshistoriepersoon{burgerservicenummer}
- /partnerhistoriepersoon/{burgerservicenummer}
- /verblijfstitelhistoriepersoon/{burgerservicenummer}

**Comment by JohanBoer** [comment]
Inmiddels is vorige week besloten dat de veblijfsplaats geen aparte resource (entiteit) is, maar een gegevensgroep van de ingeschreven persoon. Daarmee wordt het dus een eigenschap van de ingeschreven persoon. De verblijfsplaats historie kan nu dus gewoon opgevraagd worden door de ingeschrevennatuurlijkpersoon op te vragen met een als parameters de periode waarover je de historie wilt ontvangen. Volgens mij komt daarmee de endpoint /verblijfsplaatshistorie te vervallen. Gaarne bespreken op 12-10.

**Comment by gertjanvanderkooij** [comment]
Als ik naar de mogelijkheden van de historische gegevens kijk, dan lijkt het er op dat het uitgangspunt nu is dat de API door de gemeente wordt gebruikt in haar rol als 'Gemeente als afnemer' (Gemeente xyz/Algemene gemeentetaken; zie eerder doorgestuurde autorisatietabel afnemer 510001). 

Historie die ik vanuit deze invalshoek dan mis, is die van de persoonsgegevens zelf (Anr, BSN en Naamsgegevens; zie ook:
![afbeelding](https://user-images.githubusercontent.com/43776436/47666416-c8370000-dba3-11e8-896b-4bb98d71da38.png).

Kijk ik naar de mogelijkheden van de uit te wisselen gegevens, dan is hier nu meer mogelijk dan opgenomen in de genoemde autorisatietabel (bv. Datum ingang familierechtelijke betrekking, reisdocumentgegevens e.a.). 

**Vragen:**
Welk uitgangspunt is/wordt gehanteerd bij het bereik van de gegevensset en het gebruik van de Bevraging-API? Speelt hier de GBA-autorisatietabel een rol en in welke hoedanigheid zien we de gemeente dan? 

In de functionele specificaties is aangegeven dat we het model van de GBA (BRP) volgen. Als ik nu naar de onderliggende 'modellen' kijk, lijken we met deze API in twee werelden te leven; GBA en StUF ... daar waar de GBA lekker plat is, wordt in de API gestoeid met 'Gerelateerde entiteiten'. Ook zie ik bv. bij de Kindgegevens een 'Datum ingang familierechtelijke betrekking', die in de GBA alleen bij de Ouders voor komt.  

**Vragen:**
1) Wat is nu echt leidend bij de realisatie van deze Bevraging-API? Het model van de GBA, de RSGB, de vraag vanuit de Business of ... loopt alles nu een beetje door elkaar?
2) Is/wordt dit nu een API waarvan we de specificaties ooit een keer zullen voorleggen aan RvIG voor de realisatie ervan? 

Ik zou hier graag een keer over afstemmen om er een beter beeld bij te krijgen en gerichter te kunnen reageren op de lopende ontwikkelingen. @fsamwel ; Frank/Johan; kunnen we hier op korte termijn een afspraak voor maken?

**Comment by CathyDingemanse** [comment]
> Als ik naar de mogelijkheden van de historische gegevens kijk, dan lijkt het er op dat het uitgangspunt nu is dat de API door de gemeente wordt gebruikt in haar rol als 'Gemeente als afnemer' (Gemeente xyz/Algemene gemeentetaken; zie eerder doorgestuurde autorisatietabel afnemer 510001).
Dat klopt. Echter, de autorisatietabel geldt alleen voor personen buiten de gemeentegrenzen, zoals al eerder aangegeven. 

> 
> Historie die ik vanuit deze invalshoek dan mis, is die van de persoonsgegevens zelf (Anr, BSN en Naamsgegevens; zie ook:
> ![afbeelding](https://user-images.githubusercontent.com/43776436/47666416-c8370000-dba3-11e8-896b-4bb98d71da38.png).
Er is geen binnengemeentelijke afnemer bekend die deze behoefte heeft.

> Kijk ik naar de mogelijkheden van de uit te wisselen gegevens, dan is hier nu meer mogelijk dan opgenomen in de genoemde autorisatietabel (bv. Datum ingang familierechtelijke betrekking, reisdocumentgegevens e.a.).
Tabel is niet van toepassing op gegevens van personen die in de bevragende gemeente gevestigd zijn.

> 
> **Vragen:**
> Welk uitgangspunt is/wordt gehanteerd bij het bereik van de gegevensset en het gebruik van de Bevraging-API? Speelt hier de GBA-autorisatietabel een rol en in welke hoedanigheid zien we de gemeente dan?
GBA autorisatietabel speelt alleen een rol bij personen die buiten de vragende gemeente wonen. 
> 
> In de functionele specificaties is aangegeven dat we het model van de GBA (BRP) volgen. Als ik nu naar de onderliggende 'modellen' kijk, lijken we met deze API in twee werelden te leven; GBA en StUF ... daar waar de GBA lekker plat is, wordt in de API gestoeid met 'Gerelateerde entiteiten'. 
Kun je uitleggen waarom dit lijkt op StUF? 

Ook zie ik bv. bij de Kindgegevens een 'Datum ingang familierechtelijke betrekking', die in de GBA alleen bij de Ouders voor komt.
Klopt! Moet worden aangepast


> 
> **Vragen:**
> 
> 1. Wat is nu echt leidend bij de realisatie van deze Bevraging-API? Het model van de GBA, de RSGB, de vraag vanuit de Business of ... loopt alles nu een beetje door elkaar?
De businessvraag van binnengemeentelijke afnemers is leidend. 

> 2. Is/wordt dit nu een API waarvan we de specificaties ooit een keer zullen voorleggen aan RvIG voor de realisatie ervan?
Jazeker!
> 
> Ik zou hier graag een keer over afstemmen om er een beter beeld bij te krijgen en gerichter te kunnen reageren op de lopende ontwikkelingen. @fsamwel ; Frank/Johan; kunnen we hier op korte termijn een afspraak voor maken?

**Comment by JohanBoer** [comment]
> > Ook zie ik bv. bij de Kindgegevens een 'Datum ingang familierechtelijke betrekking', die in de GBA alleen bij de Ouders voor komt.
> 
> Klopt! Moet worden aangepast

Betekent dit dat ik uit de Kind_relatie de geldigVan en de geldigTotenMet zou moeten verwijdern? 
De term familierechtelijke betrekking komt nu niet in de OAS voor.

En als we over die relatie bezig zijn, is de ouder-aanduiding dan van belang, of hoort die ook niet in de kind-relatie thuis ?

**Comment by gertjanvanderkooij** [comment]
> Er is geen binnengemeentelijke afnemer bekend die deze behoefte heeft.

OK. In autorisatiebesluit lees ik dat historie categorie 01 is opgenomen "_ter uitvoering van wettelijke taken op de volgende gebieden:_"
1) Dispensatie niet-openbare archiefstukken op verzoek
2) Burgerlijke stand op verzoek

Wellicht nog te verifiëren; indien niet meer van toepassing, dan inderdaad niet nodig.

**Comment by gertjanvanderkooij** [comment]
> Kun je uitleggen waarom dit lijkt op StUF?

De modellen/schema's die nu gedefinieerd zijn voor de uitvoer meer BG dan GBA. Als de server-kant van de API ooit door RvIG zal worden gerealiseerd, vraag ik me af of zij de gegevens cf. dit model zullen aanleveren. Daarnaast verwacht ik niet dat zij afgeleide gegevens als 'voorletters', 'opgemaakte naam', 'geldigTotEnMet' zullen verstrekken. Dit zullen zij overlaten aan de afnemer zelf. Dit gebaseerd op ervaringen vanuit Operatie BRP. 

Is de gedachte dan dat via de NLX een PL in GBA-formaat wordt opgevraagd bij de GBA-V en de transformatie naar model/schema's in deze API binnen de NLX wordt gedaan?

**Comment by ehotting** [comment]
NLX doet geen transformatie of orchestratie en gaat dat ook nooit doen. API op een bron moet die bron ontsluiten, het is niet handig een API te specificeren op een manier die de bron niet levert. Waar wordt de API dan op geïmplementeerd, indien niet op de GBA?

Als onverhoopt toch transformatie nodig is moet men een ESB gebruiken (overkill) of daar een aparte service / API voor gebruiken.

**Comment by CathyDingemanse** [comment]
Ik stel voor om het eerst aan de eigenaar van de BRP te vragen, en niet op verondersteld gedrag te acteren.  Ik neem aan dat de BRP, net als iedere andere basisregistratie, er is voor haar gebruikers, en de doelstellingen van zo min mogelijk lokale kopieen en translatie onderschrijft. Dan vinden we vast een oplossing.

**Comment by gertjanvanderkooij** [comment]
Goed voorstel om dit zsm met RvIG op te nemen. Zo te peilen of een '2-in-1'-API (Bevraging op RSGB-Magazijn / Bevraging GBA-V), zoals ik 'm nu proef, wel realistisch is. 

Voor wat betreft het vullen van afgeleide velden als voorletters en opgemaakte naam ligt dit waarschijnlijk anders (minder gevoelig vanwege zelfde behoefte andere afnemers en positief effect op autorisatietabellen) dan de nu gekozen structuur en afleiden/verstrekken van generieke veld GeldigTotEnMet (hoe met andere afnemers, altijd dekkend af te leiden, juridische lading). 

Dit nog even ter informatie; ik stop nu met veronderstellen ;-); tijd voor afstemming. 

@fsamwel Hoe zie jij dit?

**Comment by JohanBoer** [comment]
Er is een specifieke userstory voor de historie bevragingen (#64 )  Alle andere besproken onderwerpen zijn geadresseerd.
