### ISSUE TITLE
Attributen met de naam UUID moeten wel een UUID zijn anders ontstaat verwarring

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#102]
# Impediment

Volgens de [OAS](
https://rebilly.github.io/ReDoc/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/openapi.yaml#operation/anderpersonenUuid) bij anderpersonenUuid is een `uuid` een:

"viercijferige gemeentecode gevolgd door een volgnummer van 13 cijfers met voorloopnullen"

Dat is het natuurlijk niet.

"Een UUID is een nummer van 128 bits (= 16 bytes). UUID wordt weergegeven in 32 ​​hexadecimale cijfers. Deze cijfers zijn ingedeeld in vijf groepen, in ongelijk aantal en gescheiden door koppeltekens: 8-4-4-4-12" - Bron: [Wikipedia](https://nl.wikipedia.org/wiki/Universally_unique_identifier)

Of het attribuut moet anders heten of de omschrijving en waardes moeten echt een UUID zijn.

**Comment by fsamwel** [comment]
Dank je Joeri. Goede observatie, is inderdaad niet correct.

Maar endpoint onderpersonen gaan we eruit halen, dus dat lost zichzelf op.

**Comment by JohanBoer** [comment]
😔....  Ga ik aanpassen.
