### ISSUE TITLE
Modellering geboorte onnodig complex

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#103]
De modellering van geboorte van een ingeschreven persoon is nu zo dat dit bijvoorbeeld leidt tot:
```
        "geboorte": {
          "geboorteplaats": "Nieuwegein",
          "geboortedatum": {
            "jaar": 2018,
            "datum": "2018-11-29",
            "maand": "11",
            "dag": "29"
          },
          "landGeboorte": {
            "landcode": "6030",
            "landnaam": "Nederland"
          }
        },
```
Om op geboortedatum te zoeken hebben we nu parameter "geboorte__geboortedatum".

Paar dingen hierover:
1. Het woord "geboorte" wordt nu nog herhaald in de attribuutnamen. Het zit al in de groep "geboorte", dus "plaats" en "datum" en "land" is dan genoeg. Idem voor tabel "land" waarbinnen "code" en "naam" lang genoeg zijn.
2. De zoekparameter klopt eigenlijk niet. Wanneer je dit consequent doorvoert moet het zijn "geboorte__geboortedatum__datum". Of wanneer je vorige punt doorvoert "geboorte__datum__datum". Maar dat wordt er niet beter op. Consequent zijn is niet altijd beter, óf het laat je zien dat modellering simpeler kan.
3. Er zit onnodig diepte in de gegevens. Kan makkelijker.

Mijn voorstel:
```
        "geboorte": {
          "datum": "2018-11-29",
          "jaar": 2018,
          "maand": "11",
          "dag": "29"
          "plaats": "Nieuwegein",
          "land": {
            "code": "6030",
            "naam": "Nederland"
          }
        },
```
En dat leidt dan tot zoekparameter "geboorte__datum", wat er weer netjes uitziet, consequent is met de afspraak over vormgeving parameters, en direct te begrijpen wat het is.

**Comment by fsamwel** [comment]
land verwijst naar GBA tabel 34. Die nemen we op met zowel de code als de omschrijving. Deze twee gegevens horen nauw bij elkaar. Vandaar dat het gegroepeerd is. Dit doen we in de API consequent op alle attributen waar een waarde uit een GBA tabel wordt gebruikt.

**Comment by gertjanvanderkooij** [comment]
Is een beetje hinken op 2 gedachten. 'Datum', 'jaar', 'maand''  en 'dag' horen ook nauw bij elkaar, maar zijn niet gegroepeerd.

Wat maakt dat attributen in een groep die verwijzen naar een tabel persé gegroepeerd moet worden?

**Comment by fsamwel** [comment]
Je hebt gelijk, niet helemaal consequent. Is vooral gevoed door de zoek-parameter van de geboortedatum die eigenlijk "geboorte__datum__datum". Dat je dus drie niveaus diep moet voor die datum. Het is maar een kwestie van smaak, of wat je makkelijk en duidelijk vindt.

**Comment by gertjanvanderkooij** [comment]
De relatie met gebruik van de geboortedatum begrijp ik. Waarom 'land' niet zo behandeld kan worden begrijp ik nog niet. Wordt in fields-parameters (en wellicht ooit als zoekparameter) nu ook 3 diep van 'geboorte__land__code' (... geen herhaling van 'datum__datum', da's wel waar). 

Vraag is meer wat de overweging is om i.g.v. element met 'tabelverwijzing' de 'code' en 'naam'  wel als 'groep' te zien.

**Comment by gertjanvanderkooij** [comment]
Brengt me op een ander 'gebruiksaspect' waar we bij het niet meer nesten van de 'geboortedatum' rekening mee moeten houden; de inrichting van de 'lokale autorisatie' en het gebruik van de 'fields-parameter'. 

Als we niet meer nesten, is dan niet de consequentie dat we naast de 'geboortedatum' ook 'geboorte__jaar', 'geboorte__maand' en 'geboorte__dag' voortaan uitgesloten moeten worden? Geldt dat voor alle datum-velden? 

Kun je ook als extra feature uitleggen ... je kunt dan zoeken/autoriseren/fieldsen tot op het niveau van bv. 'geboortejaar'. Als dit een gebruikerswens is, dan OK.

**Comment by gertjanvanderkooij** [comment]
Als laatste n.a.v. dit voorbeeld:
1) Waarom is 'geboorte__datum' opgemaakt; waarom niet zonder 'streepjes' zoals in GBA'. Dit 'rekent' vermoedelijk makkelijker en formaat met jaar vooraan, zal niet meest gebruikt worden. Consumers moeten opmaak waarschijnlijk toch omzetten.
2) Hoe ziet een geheel en deels onbekende datum er straks uit in deze structuur?
