### ISSUE TITLE
verwijzing naar fields csv opnemen in fields feature

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#1060]
Nu staat alleen nog een verwijzing naar de fields-mapping, die relevant is voor de provider. De verwijzing naar fields-Persoon.csv en fields-PersoonBeperkt.csv die relevant is voor de client developer staat er nog niet in. Juist die willen we toevoegen.

Zie ook description van fields parameter zoals beschreven in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1049#discussion_r871450750

**Comment by fsamwel** [comment]
verwijzing naar csv in fields feature is gedaan in PR #1066. Wat hier nu overblijft is description in specificaties voor fields parameter

**Comment by melsk-r** [comment]
Is in voorzien m.b.v. PR #1070.
