### ISSUE TITLE
behoefte aan reisdocumenten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#1169]
- zijn reisdocumentnummers in Personen API nodig?
- is er in de reisdocumenten API behoefte aan meer informatie dan indicatie geldigheid?

**Comment by CathyDingemanse** [comment]
De reisdocumenten API geeft invulling aan de behoefte van handhavers en marktvergunning: verificatie van het reisdocument.

Conform verificatieregister BV BSN: 

Documenttype 1: “Document met nummer <<documentnummer>> staat niet geregistreerd als gestolen of vermist".

Ander documenttype dan type 1: " “Document met nummer <<documentnummer>> kan gebruikt worden als 
 identiteitsdocument volgens de WID artikel 1"

Document is geen identiteitsdocument:  “Document met nummer <<documentnummer>> kan niet gebruikt 
worden als identiteitsdocument volgens de WID artikel 1

**Comment by fsamwel** [comment]
reisdocumenten dus verwijderen uit specificaties. feature reisdocumenten verplaatsen naar reisdocumenten repo.
