### ISSUE TITLE
Als gemeente wil ik dat gebruikers alleen gegevens krijgen waartoe ze geautoriseerd zijn

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#12]
...zodat we voldoen aan wettelijke eisen.

**Acceptatiecriteria**
- [ ] In de API specificaties is beschreven dat de provider alleen gegevens terug mag geven als er autorisatie is voor de resource
- [ ] In de API specificaties is beschreven dat de provider alleen voorkomens van de resource mag teruggeven waar de gebruiker voor geautoriseerd is
- [ ]  In de API specificaties is beschreven dat de provider alleen properties terug mag geven in het antwoord waar de gebruiker voor geautoriseerd is

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Kloppen deze 3 acceptatiecriteria? Geld autorisatie-filtering ook op niveau van voorkomens?

**Comment by CathyDingemanse** [comment]
> Kloppen deze 3 acceptatiecriteria? Geld autorisatie-filtering ook op niveau van voorkomens?

Ja, de autorisatie voor personen met een verblijfsadres binnen of buiten de eigen gemeente verschilt.

**Comment by gertjanvanderkooij** [comment]
Formeel bepaalt de rol van de gemeente m.i. de autorisatie voor zowel de binnen- als de buitengemeentelijke personen.

In de GBA-Autorisatietabel onderscheiden we 'gemeente als bijhouder' (bv. Afnemer 059901 Gemeente Rotterdam/Burgerzakentaken) en de 'gemeente als afnemer' (bv. Afnemer 510001 Gemeente Rotterdam/Algemene gemeentetaken). 

De eerste rol heeft volledige autorisatie (gehele persoonslijst; alle gegevens en alle historie), de tweede een veel beperktere; zowel qua gegevenselementen als qua historie (zie ook Autorisatietabellen GBA: [http://publicaties.rvig.nl/Landelijke_tabellen/Zoekpagina_tabel_35_autorisatietabelregel]. Het maakt niet uit of betreffend persoon in de gemeente woonachtig is of niet. 

Voor andere partijen (zie dezelfde GBA-autorisatietabel 35) die mogelijk ook toekomstig gebruiker van de Bevraging-API worden gelden weer andere autorisaties. 

Wordt hier nog onderscheid in gemaakt; zoja in de vorm van een aparte API's (bv. 'Bevraging als Bijhouder' en 'Bevraging als Afnemer'). Of wordt dit geheel binnen de Autorisatie-component geregeld. 

**NB.** Vanuit de GBA worden voor de zogenaamde spontane en selectieverstrekkingen ook Voorwaarde-regels opgesteld (doelbinding-autorisatie). Ik kijk nog even na of een dergelijk constructie ook toegepast wordt voor 'Adhoc'-verstrekkingen (lees Bevragingen). Of er bijvoorbeeld afnemers zijn die allen personen mogen bevragen t/m bepaalde leeftijd of woonachtig in een bepaald verzorgingsgebied).

**Comment by JohnRooijakkers** [comment]
> risatie voor personen met een verblijfsadres binnen of buiten de eigen gemeente verschilt.

Kun je aangeven wat het verschil is en waar dat is bepaald?

**Comment by JohnRooijakkers** [comment]
Het lijkt me goed dat vastgesteld wordt op basis van welke criteria (kenmerken van de consumer) de autorisatie wordt bepaald door de provider. Binnen de huidige StUF standaard beperkt zich dit tot de organisatie, applicatie en gebruiker. Een gemis hier is de "reden" waarom de gegevens worden opgevraagd (doelbinding). Gaan we deze binnen de nieuwe API's wel opnemen?

Binnen het autorisatiebesluit voor gemeenten als afnemers wordt onderscheid gemaakt tussen diverse gegevenssets die ad hoc opgevraagd mogen worden per doelbinding. Maar voor zover mij bekend is dit onderscheid niet terug te zien in de autorisatietabelregel voor deze afnemers. Het is daarom de vraag of we bij de nieuwe API's willen uitgaan van de bestaande autorisatietabelregels of de formele autorisatiebesluiten.

**Comment by gertjanvanderkooij** [comment]
Ik kan me in deze fase wel vinden in het standpunt dat in de functionele specificaties is opgenomen:
_"De API levert alleen gegevens terug waar de vragen organisatie (bv. gemeente Rotterdam als afnemer) geautoriseerd is. De vragende applicatie is verantwoordelijk voor het filteren van het antwoord op autorisatie van de gebruiker."._ Hiermee aan te sluiten op de huidige werkwijze. 

Een concrete vertaling naar een doelbinding (voorwaarderegels) op basis van de bepalingen in het autorisatiebesluit is in de meeste gevallen niet te maken, omdat hiervoor ook gegevens nodig zijn die niet in de BRP zijn opgenomen. Daar waar deze (deels) wel te maken is (bv. een bepaald verzorgingsgebied), zijn ze door RvIG opgenomen in de autorisatietabellen. Ter illustratie heb ik het autorisatiebesluit voor afnemer 51001 bijgesloten: 
[510001 Gemeente Rotterdam BRP 1-7-2018.pdf](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2518278/510001.Gemeente.Rotterdam.BRP.1-7-2018.pdf)

**Comment by CathyDingemanse** [comment]
> Formeel bepaalt de rol van de gemeente m.i. de autorisatie voor zowel de binnen- als de buitengemeentelijke personen.
> 
> In de GBA-Autorisatietabel onderscheiden we 'gemeente als bijhouder' (bv. Afnemer 059901 Gemeente Rotterdam/Burgerzakentaken) en de 'gemeente als afnemer' (bv. Afnemer 510001 Gemeente Rotterdam/Algemene gemeentetaken).
> 
> De eerste rol heeft volledige autorisatie (gehele persoonslijst; alle gegevens en alle historie), de tweede een veel beperktere; zowel qua gegevenselementen als qua historie (zie ook Autorisatietabellen GBA: [http://publicaties.rvig.nl/Landelijke_tabellen/Zoekpagina_tabel_35_autorisatietabelregel]. Het maakt niet uit of betreffend persoon in de gemeente woonachtig is of niet.

Bovenstaande is vrees ik niet correct. De autorisatietabellen waar hier naar wordt verwezen (gemeente als afnemer) gelden alleen voor het raadplegen van de GBA-V. Dit is in principe alleen toegestaan voor personen die niet in de betreffende gemeente wonen. Autorisatiebesluiten van binnengemeentelijke afnemers voor het gebruik van gegevens personen die binnen de gemeente gevestigd zijn worden door B&W genomen, en niet door BZK. BZK gaat alleen over de autorisatie van gemeenten als afnemer van buitengemeentelijke personen.

**Comment by CathyDingemanse** [comment]
Deze API levert alle personen die zich in NL hebben ingeschreven, en ook niet ingezetenen (RNI). 
Als een gemeente (in haar rol afnemer) deze API bevraagt heeft zij recht op ALLE gegevens van personen die binnen haar gemeentegrenzen wonen, en van personen die buiten haar gemeentegrenzen verblijven krijgt zij gegevens conform de hierboven genoemde RvIG autorisatietabellen. 
Dit filter moet door de provider voor gemeentelijke afnemers worden geimplementeerd.

Binnengemeentelijk worden additionele filters toegepast conform de rechten van afnemende applicatie en gebruikers die op basis van doelbinding zijn bepaald.

**Comment by gertjanvanderkooij** [comment]
Yep, je hebt gelijk :-) 

Ik heb het betreffende autorisatiebesluit voor de 'Gemeente als Afnemer' er nog even op nagelezen en aan het eind staat het er duidelijk:
_"In het onderhavige autorisatiebesluit wordt de gemeente geautoriseerd voor het verstrekt krijgen van gegevens uit de basisregistratie personen van ingeschrevenen die niet zijn ingeschreven in de gemeente Rotterdam. Ingeschrevenen die zijn ingeschreven in gemeente Rotterdam vallen niet binnen de doelgroep en over deze personen mogen op grond van dit autorisatiebesluit aldus geen gegevens worden opgevraagd uit de basisregistratie personen."_

Volgende vragen heb ik nog:
1) Wie beschouwen we in deze fase als 'de provider van deze API' (_"Deze API levert alle personen die zich in NL hebben ingeschreven, en ook niet ingezetenen (RNI)."_ 
2) Biedt deze API voor binnengemeentelijk gebruik nu voldoende gegevens; ook voor de personen die in de gemeente zijn ingeschreven? 
3) Moeten we voor deze API nog rekening houden met de rol van 'Gemeente als bijhouder'; dan heeft de gemeente ongeacht de gemeente van inschrijving toch recht op alle gegevens van een ingeschreven persoon?

**Comment by JohanBoer** [comment]
> Yep, je hebt gelijk :-)
> 
> Ik heb het betreffende autorisatiebesluit voor de 'Gemeente als Afnemer' er nog even op nagelezen en aan het eind staat het er duidelijk:
> _"In het onderhavige autorisatiebesluit wordt de gemeente geautoriseerd voor het verstrekt krijgen van gegevens uit de basisregistratie personen van ingeschrevenen die niet zijn ingeschreven in de gemeente Rotterdam. Ingeschrevenen die zijn ingeschreven in gemeente Rotterdam vallen niet binnen de doelgroep en over deze personen mogen op grond van dit autorisatiebesluit aldus geen gegevens worden opgevraagd uit de basisregistratie personen."_
> 
> Volgende vragen heb ik nog:
> 
> 1. Wie beschouwen we in deze fase als 'de provider van deze API' (_"Deze API levert alle personen die zich in NL hebben ingeschreven, en ook niet ingezetenen (RNI)."_

De RvIG en/of Gemeentelijke bron 

> 2. Biedt deze API voor binnengemeentelijk gebruik nu voldoende gegevens; ook voor de personen die in de gemeente zijn ingeschreven?

Ja

> 3. Moeten we voor deze API nog rekening houden met de rol van 'Gemeente als bijhouder'; dan heeft de gemeente ongeacht de gemeente van inschrijving toch recht op alle gegevens van een ingeschreven persoon?

Nee, deze API is voor de gemeente als Afnemer bestemd
