### ISSUE TITLE
Is er behoefte aan de ouderaanduiding?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#123]
In GBA heeft een persoon een ouder1 (02/52) en ouder2 (03/53). In het RSGB en in onze API dat samengevoegd tot "ouder" met daarin een attribuut "ouderaanduiding". De ouderaanduiding kan de waarde 1 of 2 hebben.

Is er behoefte aan de ouderaanduiding? We nemen dan een attribuut op dat niet als zodanig in GBA zit. Ik kan me ook niet bedenken dit dit in enig proces relevant is.

Vandaar de vraag: moeten we attribuut "ouderaanduiding" opnemen in het bericht?

**Comment by gertjanvanderkooij** [comment]
Voor wat betreft de regsitartie van oudergegevens grofweg volgende situaties mogelijk cf. huidig LO GBA (zie ook HUP; evt. verdere navraag domeinspecialisten):

- Als een persoon twee ouders heeft, met maakt het geen verschil of de gegevens van de ouder uit wie het kind is geboren of de ouder uit wie het kind niet is geboren in categorie 02-Ouder1 of categorie 03-Ouder2 worden opgenomen. Er kan echter maar één categorie 02-Ouder1 worden opgenomen en één categorie 03-Ouder2.

- Als een persoon één ouder heeft dan worden de gegevens van deze ouder opgenomen in categorie 02-Ouder1.

- Zijn de oudergegevens onbekend, dan worden conform LO GBA de standaardwaarden in de rubrieken van categorie 02 (en eventueel 03) gevuld.

- Is er sprake van het feit dat er juridisch geen ouders zijn, dan worden van categorie 02 (en eventueel 03) alleen de groepen 81-Akte of 82-Document, 85-Geldigheid en 86-Opneming gevuld. 

**Let op!** Indien er sprake is van Gezag (categorie 11-Gezagsverouding), dan wordt via het attribuut 32.10 (Indicatie gezag minderjarige) verwezen naar resp. Ouder 1, Ouder 2 of een Derde. De inhoud van dit attribuut kan de volgende waarden aannemen: 1, 2, D, 1D, 2D, 12 (zie LO GBA 3.10 blz. 288). In dat geval is het dus van belang om te weten wie ouder 1 en wie ouder 2 is. 

Dit zal de reden zijn dat de ouderaanduiding in de RSGB is opgenomen en zal/kan ook de reden zijn deze voor de API ook op te moeten nemen.

**Comment by fsamwel** [comment]
categorie 11-Gezagsverhouding is nu niet opgenomen in de api. Moet er m.i. wel in (zit ook in autorisatietabellen van D.H.; én zat ook in RSGB/bg0310).

@JohanBoer voeg jij attribuut 32.10 Indicatie gezag minderjarige toe

**Comment by JohanBoer** [comment]
Conclusie, in de API-spec wordt conform GBA een ouderaanduiing opgenomen waarmee kan worden aangegeven werden of het 02-Ouder1 of 03-Ouder2 betreft.
