### ISSUE TITLE
Persoonslijst versus relationeel model voor kinderen, ouders en partners

### ISSUE THREAD

**Issue by mvdbro** [VNG-Realisatie/Bevragingen-ingeschreven-personen#128]
De API specificatie specificeert voor de oudergegevens ‘Het ophalen de ouder-gegevens van een Ingeschreven Persoon zoals die op de persoonslijst voorkomen.’ hetzelfde geldt voor kinderen en partners. Met deze keuze wordt voor deze relaties de relationele modellering in het RSGB los gelaten.

Het komt in de GBA voor dat de gegevens van een gerelateerde persoon afwijken van de gegevens van de ingeschreven persoon met hetzelfde burgerservicenummer. Voor een gebruiker van de API kunnen deze afwijkingen verrassend zijn. Om zeker te zijn dat je de geldende gegevens van een gerelateerde persoon gebruikt zal je deze gerelateerde persoon moeten ophalen als ingeschreven persoon obv het burgerservicenummer.

Als je de modellering van het RSGB volgt, dan krijg je in veel gevallen automatisch de correcte gegevens. Het is dan wel wenselijk dat aangegeven kan worden of de getoonde gegevens afkomstig zijn van de ingeschreven persoon of van een gerelateerde persoon.

Als je de GBA modellering volg (is niet mijn keuze), dan is het voor de gebruiker helderder om in de API de kinderen, ouders en partners niet op te nemen als relaties, maar als groepen binnen ingeschreven persoon. Je wekt dan niet de suggestie dat je werkt met een relationeel model en sluit keurig aan bij de categorieën in de GBA. Als de gerelateerde een burgerservicenummer bevat, kan je in de groep een link opnemen naar de ingeschreven persoon met dat burgerservicenummer, zodat desgewenst snel gecheckt kan worden of de gegevens correct zijn of om de overige gegevens van die persoon te zien.

**Comment by ehotting** [comment]
> Het komt in de GBA voor dat de gegevens van een gerelateerde persoon afwijken van de gegevens van de ingeschreven persoon met hetzelfde burgerservicenummer.

Is dat een foutsituatie die, zodra ontdekt, zo snel mogelijk hersteld dient te worden door de verantwoordelijke gemeente?

**Comment by fsamwel** [comment]
Ik denk dat het de bedoeling is dat:
1. voor een persoon alleen die attributen van de partner, ouders en kinderen worden getoond die op de PL van de persoon voorkomen
2. de vulling van die attributen gehaald moet worden uit de gerelateerde personen wanneer het ingeschreven personen betreft

Het eerste zorgt voor privacy by design, de tweede zorgt voor juiste actuele gegevens.

@CathyDingemanse @gertjanvanderkooij @JohanBoer Zien jullie dit ook zo?
Zo ja, dan moet dit duidelijk worden gespecificeerd in de API specificatie.

**Comment by gertjanvanderkooij** [comment]
Deze is lastig en kan leiden tot weer andersoortige afwijkingen ten opzichte van de GBA PL. Bv. in die gevallen dat een (ex-)partner na sluiting/ontbinding een naamswijziging (of geslachtswijziging) heeft ondergaan. Via de API wordt dan de actuele situatie van de gerelateerde partner doorgegeven, die dan afwijkt van de gegevens op de GBA PL. 

Of willen we in de API-specificatie opnemen dat de gegevens van de gerelateerde worden gevuld op basis van de peildatum (bv. igv huwelijk/partnerschap is de peildatum dan datum sluiting/ontbinding; dit afhankelijk van status huwelijk.  

_**NB.** Ik weet dat we hier tijdens oBRP ook even mee hebben gestoeid. Ik zoek even na wat we hier uiteindelijk hebben besloten!_

Los daarvan is mijn voorstel dat Cathy nog even afstemt met domeindeskundigen. Is er ook één voor op de lijst om (later) met RvIG te bespreken.

**Comment by CathyDingemanse** [comment]
> Ik denk dat het de bedoeling is dat:
> 
> 1. voor een persoon alleen die attributen van de partner, ouders en kinderen worden getoond die op de PL van de persoon voorkomen
> 2. de vulling van die attributen gehaald moet worden uit de gerelateerde personen wanneer het ingeschreven personen betreft
> 
> Het eerste zorgt voor privacy by design, de tweede zorgt voor juiste actuele gegevens.
> 
> @CathyDingemanse @gertjanvanderkooij @JohanBoer Zien jullie dit ook zo?
> Zo ja, dan moet dit duidelijk worden gespecificeerd in de API specificatie.

Ja ik zie dat ook zo. Hoe erg is het dat de gegevens afwijken van de GBA PL? Onjuiste gegevens verstrekken is erger. Het zou mij overigens niets verbazen als dat in het RSGB model ook al zo werkt.

**Comment by gertjanvanderkooij** [comment]
Hij blijft lastig en kan ook gevoelig zijn; bv. in volgend geval ... (ik weet het; het komt niet vaak voor, maar als het voor komt wil je het niet verkeerd doen). Hoe erg is het bv. in onderstaande casus:

Frans en Carolien zijn getrouwd. Carolien is transgender en besluit tot naams- en geslachtswijziging. Frans begrijpt Carolien volledig; zij besluiten hun huwelijk te ontbinden en ieder hun weg te gaan. Een jaar na de huwelijksontbinding gaat Carolien voortaan als man door het leven en noemt hij zich Carl. De wijzigingen worden op de PL van Carolien (vanaf dan Carl) in de BRP doorgevoerd. De PL van Frans blijft ongewijzigd. Op zijn PL blijft hij getrouwd geweest met Carolien (V).

Als we doen wat wordt voorgesteld is het ontbonden huwelijk van Frans (is actuele situatie van het huwelijk) er één met een man, namelijk Carl. En dat wil hij nu net niet.

**Comment by ehotting** [comment]
Yep, dit is precies waarom de BRP met Event Sourcing moet gaan werken en het hele concept PL niet werkt in digitale werkelijkheid. Met Event Sourcing is dit geen issue.

**Comment by mvdbro** [comment]
@gertjanvanderkooij : Bij het werken met Paraplu in Amsterdam is bij mij het beeld ontstaan dat de gegevens van gerelateerden op een persoonslijst door fouten bij het opvoeren van die gegevens in sommige gevallen afwijken van dezelfde gegevens op de persoonslijst van die gerelateerde zelf. Zou je kunnen aangeven of mijn beeld juist is en en zo ja wat jouw inschatting is van hoe vaak dit nu nog voorkomt en of er inmiddels gericht actie wordt ondernomen om dit soort problemen weg te werken.

Het voorbeeld dat Gert Jan geeft kan ook pijnlijk zijn voor Carl, want wil hij nog wel geconfronteerd met hoe hij voorheen was?

Ik vraag me in het algemeen af of we dit probleem moeten benaderen vanuit de personen waarover een respons gegevens bevat. Het lijkt me zinniger om na te gaan aan welke gegevens de gebruikers van de API behoefte hebben en dat zijn veelal niet de personen zelf (Carl en Frans) maar processen in de gemeente die iets willen weten over een persoon. Mijn buikgevoel is dat die processen behoefte hebben aan de actuele gegevens van gerelateerde personen. In plaats van af te gaan op buikgevoel is het beter dit na te vragen bij de toekomstige gebruikers. Er is daarmee niet alleen afstemming met RiVG nodig, maar ook met de toekomstige gebruikers.

**Comment by gertjanvanderkooij** [comment]
> Bij het werken met Paraplu in Amsterdam is bij mij het beeld ontstaan dat de gegevens van gerelateerden op een persoonslijst door fouten bij het opvoeren van die gegevens in sommige gevallen afwijken van dezelfde gegevens op de persoonslijst van die gerelateerde zelf. Zou je kunnen aangeven of mijn beeld juist is en en zo ja wat jouw inschatting is van hoe vaak dit nu nog voorkomt en of er inmiddels gericht actie wordt ondernomen om dit soort problemen weg te werken

In geval van invoerfouten (verkeerd overgenomen van brondocumenten) geldt dat deze fouten zo spoedig mogelijk moeten worden hersteld.

In geval van afwijkende gegevens op het brondocument zelf, geldt dat in de GBA de gegevens van het brondocument worden gevolgd en er dus bewust wordt afgeweken van geregistreerde gegevens van deze persoon. Met de verregaande integratie van de Burgerlijke Stand in de Burgerzaken-processen komt dit soort verschillen steeds minder vaak voor. Als ik de HUP erbij pak, dan kan actualisering hiervan plaatsvinden met als brondocument 'PL gerelateerde'.    

Kan nog wel voorkomen in relatie tot ouders/kinderen/partners die ten tijde van de registratie van de hoofdpersoon zelf nog in het buitenland verblijven en zich nadien in Nederland vestigen. De eerste inschrijving van betreffende gerelateerde kan dan op basis van andere (sterkere) brondocumenten worden gedaan, waardoor afwijkingen kunnen ontstaan. Ook hier geldt bovengenoemde actualiseringsmogelijkheid met verwijzing naar 'PL gerelateerde'.

In hoeverre dit actief wordt gedaan door gemeenten is mij niet bekend. Dit na te vragen.       



> In plaats van af te gaan op buikgevoel is het beter dit na te vragen bij de toekomstige gebruikers. Er is daarmee niet alleen afstemming met RiVG nodig, maar ook met de toekomstige gebruikers.

Eens! Met name de vraag '_Hoe erg dit is in het gebruik_'. Ook vwb de genoemde casus.

**Comment by fsamwel** [comment]
bedenk me dat wanneer we bij /partners de actuele gegevens van de partner die ingeschreven persoon is gebruiken, we dit ook in partnerhistorie moeten doen. Dat is immers dezelfde resource, maar dan met tijdreizen. Wordt dan de Naams- en geslachtswijziging van de partner ook een gebeurtenis (voorkomen) in de partnerhistorie? (er wijzigt dan niks in de relatie en ook niks op de PL van de persoon, maar wel iets in de gegevens van de partner)

**Comment by ehotting** [comment]
Volgens mij zou je partnergegevens niet mee moeten geven in een response over subject. Per proces bestaat een andere behoefte: de ene keer wil je weten hoe het historisch zat met een partner, de andere keer hoe het nu zit. Door alleen de id van de partner + aanduiding periode partnerschap in de response op te geven, kan de volgende API call afhankelijk van de situatie er anders uitzien.

**Comment by mvdbro** [comment]
De hamvraag blijft wat de resource ingeschreven persoon nu precies is:
1. Een GBA PL met de gerelateerde personen als gegevens van de PL waarop de gerelateerde personen voorkomen. De gerelateerde personen zijn dan subresources die afhankelijk zijn van de persoon vanwaaruit de relatie ligt. Die subresource kan een link bevatten naar een ingeschreven persoon resource.
2. Een natuurlijk persoon zoals gemodelleerd in het RSGB en StUF bg0204 en bg0310 met voor partners, kinderen en ouders relaties naar andere natuurlijke personen. De gerelateerde personen zijn dan soortgelijke resources als de persoon vanwaaruit de relatie ligt.

Op dit moment wordt in gemeenten gewerkt met de tweede variant. Overgang naar de eerste variant zal goed moeten worden afgestemd met de gebruikers van de huidige webservices voor het bevragen van personen. Het is op dit moment ook mogelijk om van een gerelateerde persoon alle gegevens op te vragen met uitzondering van de relaties. Ook hier leidt de introductie van de API tot andere (complexere) functionaliteit.

Opsplitsen in deelfunctionaliteiten met herhaalde aanroepen is aantrekkelijk vanuit de provider gezien, maar hoeft dit niet te zijn voor de consumers. Afstemming met de consumers is derhalve noodzakelijk.

**Comment by fsamwel** [comment]
> De hamvraag blijft wat de resource ingeschreven persoon nu precies is:

Er is nu in de API duidelijk gekozen voor de eerste variant.

> Opsplitsen in deelfunctionaliteiten met herhaalde aanroepen is aantrekkelijk vanuit de provider gezien, maar hoeft dit niet te zijn voor de consumers. 

Opsplitsen kan ook aantrekkelijk zijn voor consumers. Meer eenvoudige aanroepen/antwoorden kan makkelijker zijn dan een enkele complexe. We hebben er nu voor gekozen dat beide kan. 
Alleen het in één aanroep ophalen van de gehele resource plus de hele resource van gerelateerde ingeschreven personen kan niet. Hiervoor is gekozen vanuit AVG/privacy/autorisatie perspectief. Privacy-by-design is een belangrijk architectuurprincipe voor de API's.

**Comment by mvdbro** [comment]
Kan er ook nog ingegaan worden op andere aspecten in mijn comment, zoals het ophalen van de behoeften bij de gebruikers en de migratie van de nu in gebruik zijnde web services naar de nieuwe API?

**Comment by CathyDingemanse** [comment]
> > De hamvraag blijft wat de resource ingeschreven persoon nu precies is:
> 
> Er is nu in de API duidelijk gekozen voor de eerste variant.
> 
Ja, echter:
- de subresource heeft dezelfde attributen als de categorie partner op de PL uit het LO + een link naar de ingeschreven persoon (als het een INP is)
- van de subresource worden actuele gegevens getoond. Dat is nu met de RSGB gegevensmagazijnen ook het geval. 

> > Opsplitsen in deelfunctionaliteiten met herhaalde aanroepen is aantrekkelijk vanuit de provider gezien, maar hoeft dit niet te zijn voor de consumers.
> 
> Opsplitsen kan ook aantrekkelijk zijn voor consumers. Meer eenvoudige aanroepen/antwoorden kan makkelijker zijn dan een enkele complexe. We hebben er nu voor gekozen dat beide kan.
> Alleen het in één aanroep ophalen van de gehele resource plus de hele resource van gerelateerde ingeschreven personen kan niet. Hiervoor is gekozen vanuit AVG/privacy/autorisatie perspectief. Privacy-by-design is een belangrijk architectuurprincipe voor de API's.

**Comment by CathyDingemanse** [comment]
> Volgens mij zou je partnergegevens niet mee moeten geven in een response over subject. Per proces bestaat een andere behoefte: de ene keer wil je weten hoe het historisch zat met een partner, de andere keer hoe het nu zit. Door alleen de id van de partner + aanduiding periode partnerschap in de response op te geven, kan de volgende API call afhankelijk van de situatie er anders uitzien.

Dat doen we ook niet gelukkig 👍. Je kunt als consumer alle kanten op: je krijgt in de resource alleen een  (of meer:)) links naar partner(s), en als je er expliciet om vraagt kun je die aanvullen met (een deel van) de partnergegevens door de expand parameter te gebruiken.

**Comment by CathyDingemanse** [comment]
> bedenk me dat wanneer we bij /partners de actuele gegevens van de partner die ingeschreven persoon is gebruiken, we dit ook in partnerhistorie moeten doen. Dat is immers dezelfde resource, maar dan met tijdreizen. Wordt dan de Naams- en geslachtswijziging van de partner ook een gebeurtenis (voorkomen) in de partnerhistorie? (er wijzigt dan niks in de relatie en ook niks op de PL van de persoon, maar wel iets in de gegevens van de partner)

Dit is de Frans en Carolien issue. Ik vrees dat voor de huidige afnemers van het Haagse gegevensmagazijn Frans inderdaad met Carl getrouw is geweest. Er worden nu geen events op de PL van ex-partners bijgehouden. Overigens ook niet op de PL. Die moet je reconstrueren obv historie.

**Comment by CathyDingemanse** [comment]
zie # feature https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/geslachtswijziging%20feature
