### ISSUE TITLE
indicatie onjuist (84.10) en historie partners, ouders en kinderen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#130]
Een partner, ouder of kind is niet actueel wanneer indicatie onjuist is gevuld. 

Hoe werkt dit voor historie/.../partners? Er is immers geen datum verbonden hieraan. Moet een (ex)partner met indicatie onjuist niet (nooit) worden opgenomen?

**Comment by gertjanvanderkooij** [comment]
Wordt via huidige webservice 'LO3 Adhoc Service' niet geleverd; zie LO GBA 3.10 blz. 704:

_"**C.7.3.3 Meeverstrekken**
Bij de gegevensverstrekking vanuit GBA-V aan afnemers worden gegevens over opschorting,
onderzoek, verificatie en RNI-deelnemer meeverstrekt conform de voorschriften van
paragraaf C.2.8. Als element 84.10 (Indicatie onjuist dan wel strijdigheid met de openbare orde)
voorkomt in een categorie, dan worden de gegevens uit die categorie niet verstrekt."_

Dit punt speelde ook binnen Operatie BRP. Hier waren de 'onjuist/strijdige' gegevens onderdeel van de FormeleHistorie. Indien een Afnemer was geautoriseerd voor de FormeleHistorie, dan ontving deze ook de 'onjuist/strijdig'-verklaarde gegevens. Er waren ons toendertijd echter geen Afnemers bekend die geautoriseerd waren voor de FormeleHistorie. De Gemeente in de rol van Bijhouder vanzelfsprekend wel!

Verder ter afhandeling aan PO en Domeindeskundigen (evt. in overleg met RvIG).

**Comment by CathyDingemanse** [comment]
Antwoord van onze specialist: 
Wanneer in een relatie een indicatie onjuist voorkomt mag deze nooit worden geleverd.
Dit gegeven wordt enkel bewaard bij de bronhouder. Het was zelfs de bedoeling in de nieuwe BRP deze gegevens apart op te slaan en enkel tbv reconstructies vrij te geven voor specialisten.

Mijn antwoord: er is geen behoefte aan formele historie bij afnemers. Als de indicatie onjuist bij een relatie voorkomt, deze relatie niet meegeven in het antwoord.

**Comment by fsamwel** [comment]
Duidelijk

**Comment by gertjanvanderkooij** [comment]
Dit geldt dan in z'n algemeenheid; geen enkele GBA-categorie waarin de 'indicatie onjuist' is gevuld wordt geleverd. Dus ook van toepassing op historie Verblijfplaats en Verblijfstitel. Maar bv. ook een onjuist opgenomen categorie 06 Overlijden. Dit als specificatie voor de server-implementatie.

**Comment by JohanBoer** [comment]
Dit gedrag van de provider wordt omschreven in een feature.

**Comment by CathyDingemanse** [comment]
feature schreven: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/indicatie%20onjuist%20feature
