### ISSUE TITLE
Maak zoek-met-bsn.feature werkend 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Bevragingen-ingeschreven-personen#1377]
Scenario op regel 17 werkt bij toeval (bsn staat al in de GBA-V database), maar de andere bsn's bestaan niet en worden niet opgevoerd. 
Zorg dat de personen met bsn's worden aangemaakt. 

Tevens een gba-dev variant maken omdat het zoeken en de beperking in het leveren van gegeven een GBA functionaliteit is,

n.a.v. PR #1360

**Comment by MelvLee** [comment]
Dat is gedaan. Zie nieuwe feature bestanden onder features/bevragen/raadpleeg-met-burgerservicenummer
