### ISSUE TITLE
Kiesrecht is nu niet opgenomen. Is dat terecht ?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Bevragingen-ingeschreven-personen#138]
Vraag van Kayo de Bakker n.a.v. proefimplementatie :

_Er is geen kiesrecht opgenomen terwijl dit in de GbaV te vinden is. Is dit bewust_

In het LO Gba is ook een categorie 13 kiesrecht opgenomen. Dat zou een argument kunnen zijn om dit op te nemen. 

Dit kunnen we eventueel ook in een volgende versie opnemen omdat het in de huidige behoefte-inventarisatie blijkbaar niet boven is komen druiven.

**Comment by CathyDingemanse** [comment]
Wel opnemen, er zijn in Den Haag iig 2 afnemersgroepen die dit gegeven afnemen.
Ontbrekende LO gegevens hebben niet mijn aandacht gedacht, omdat ik er vanuit ben gegaan dat alle gegevens uit LO GBA worden opgenomen in het nieuwe informatiemodel dat de basis vormt voor de API.

**Comment by JohanBoer** [comment]
Aanduiding Europees Kiesrecht is gedefinieerd als Numeriek lengte 1 met de volgende waarden : 
1 (= persoon is uitgesloten)
2 (= persoon ontvangt oproep)
Nemen we die definitie en waarden over of willen we deze als boolean definieren ?

**Comment by CathyDingemanse** [comment]
Waarden conform LO, dan is eea nog uitbreidbaar bovendien.

**Comment by JohanBoer** [comment]
Opgelost in pull request #145
