### ISSUE TITLE
Brondocumenten zijn nu niet opgenomen is dat terecht ?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Bevragingen-ingeschreven-personen#139]
Vraag van Kayo de Bakker n.a.v. proefimplementatie :

_Brondocumenten (zoals akte registraties van huwelijk of documenten bij geboorte van een persoon) zie ik niet terug in de structuur terwijl de GbaV een hoop van dit soort data heeft. Is hier voor gekozen om dit niet te tonen?_

**Comment by JohanBoer** [comment]
Groep 82 Document moet waar genoemd in LO GBA ook opgenomen worden.

**Comment by CathyDingemanse** [comment]
Brondocumenten zijn nodig (mn de gemeente waar ze zich bevinden) bijvoorbeeld voor dienstverlening mbt voorbereiding huwelijk en partnerschappen.

**Comment by gertjanvanderkooij** [comment]
Vraag:
Ik lees dat er een proefimplementatie beschikbaar is voor het testen van de API. 
a) Is deze extern benaderbaar/testbaar?
b) Welke testset hangt hieronder?

Voorstel:
Mijn voorstel is het model nu te bevriezen en een story op te voeren voor het matchen RSGB-Bevraging-model en het GBA-model, zoals we dit in een eerder overleg hebben onderkend. Op basis hiervan dan te beoordelen welke gegevens alsnog in het model moeten worden opgenomen. Dit in één keer in een volgende release te gaan doen.

**Comment by CathyDingemanse** [comment]
Bevriezen is een goed idee als de verwachting is dat het matchen op het GBA model nog veel werk zal zijn. Anders ben ik geneigd om even door te pakken en het direct goed te doen. Wij gaan hier naar verwachting een bhoorlijk aantal afnemers op aansluiten, en dan is wijzigen lastiger.

**Comment by gertjanvanderkooij** [comment]
OK, aanpak zou dan kunnen zijn:
1) Inventariseer alle autorisatiebesluiten die van toepassing zijn op gemeente als afnemer (ik heb er eerder 2 doorgestuurd, maar weet niet of dit ze allemaal zijn)
2) Bepaal op basis van autorisatiebesluiten de maximale set aan gegevens waarvoor een gemeente als afnemer geautoriseerd kan zijn
3) Vergelijk deze set met huidige model API Ingeschreven persoon
4) Beoordeel of ontbrekende elementen moeten worden toegevoegd
5) Voeg de elementen toe

**Comment by JohanBoer** [comment]
De elementen die nog toegevoegd worden zijn door de productowner in #147 beschreven. daar worden ook de elementen die een relatie met de brondocumenten hebben geadresseerd.
