### ISSUE TITLE
Er is nu 1 groep NationaliteiInOnderzoek. Als er meerdere Nationaliteiten zijn, hoe wordt dan aangegeven welke nationaliteit in Onderzoek is

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Bevragingen-ingeschreven-personen#140]
Vraag van Kayo de Bakker n.a.v. proefimplementatie :

Nationaliteit InOnderzoek heeft deze attributen, maar deze lijken dan ook voor alle nationaliteiten te gelden waar bij de GbaV een in onderzoek attribuut per nationaliteit opgenomen is. Klopt dit?

**Comment by JohanBoer** [comment]
We moeten dus een oplossing zien te vinden. Nationaliteit is de enige gegevensgroep die in onderzoek kan zijn én die meermaals voor kan komen. 
Een mogelijkheid hiervoor id om de groep NationaliteitInOnderzoek ook meermaals voor te laten komen (0..*) eb i die gorp het element Nationaliteit_id op te nemen dat een verwijzing is naar de nationaliteit die het betreft. 

Input is welkom.

**Comment by CathyDingemanse** [comment]
In overleg met Melvin: als elk van de nationaliteiten los van elkaar in onderzoek kunnen staan, graag een uuid koppelen aan een nationaliteit. Deze uuid opnemen bij "in onderzoek" om aan te geven welke nationaliteit het betreft.

**Comment by JohanBoer** [comment]
De in het vorige commentaar geschetste oplossing is achterhaald. N.a.v. de discussie in #132 wordt er voor een andere constructie gekozen.
