### ISSUE TITLE
Als consumer van de GET /ingeschrevennatuurlijkpersonen wil ik gelinkte (BAG) resources kunnen opvragen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#2]
zodat ik ook gerelateerde gegevens kan gebruiken bij de opgevraagde resource.

Op dit moment bestaat er nog geen API koppelvlak voor het ontsluiten van (bijv.) BAG gegevens. Maar vanuit BRP resources (ingeschreven natuurlijk persoon) zijn er wel relaties naar BAG gegevens. De API voor het opvragen van de ingeschreven persoon moet dus URI's kunnen samenstellen die verwijzen naar de betreffende BAG-objecten en waar deze BAG-objecten ook daadwerkelijk op te vragen zijn. Dus voor alle gelinkte resources moet er binnen het Bevragen ingeschreven personen koppelvlak (ten minste tijdelijk) een resource API beschreven (ontsloten) zijn.

**Acceptatiecriteria**
- [ ] Voor elke gelinkte resource is er een GET-operatie op de resource beschikbaar
- [x] Voor een gelinkte resource buiten het BRP-domein wordt alleen het opvragen van de actuele status van de enkele resource gespecificeerd

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Het realiseren van een endpoint voor de nummeraanduiding is buiten scope geplaatst. Dat wil niet zeggen dat het niet nodig is.
