### ISSUE TITLE
Huidige master versie OAS werkt niet

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#25]
# Impediment

Hij parsed niet = Invalide YAML. Ook zie ik een hoop dubbellingen.

Zie: http://rebilly.github.io/ReDoc/?url=https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/api-specificatie/BRPB1.0.yaml

**Comment by JohanBoer** [comment]
Net samen naar gekeken en in Swagger parsed hij wel. Kijk jij er zelf nog naar waarom hij bij jou niet Parsed ?

**Comment by joeribekker** [comment]
Dubbelingen zijn weg bij laatste master.

Vreemd, als ik em copy/paste in SwaggerHub gaat het goed maar via de petstore niet. Rebilly ondersteund nog niet alle OAS3 attributen, dus die kan daarom fout gaan.

Lijkt me echter goed om een OAS check in te bouwen in de CI-straat :)
