### ISSUE TITLE
tabel-entiteiten worden domeinwaarden

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Bevragingen-ingeschreven-personen#31]
##Verander tabel-entiteiten in domeinwaarden (discussie 24/9 fieldlab).

Schema componenten voor tabelentiteit en enumeraties krijgen vaste extensie
Schema componenten voor tabel-entiteiten en enumeraties krijgen extensie "\_tabel" en "\_enum".

*Ratio*
Er kunnen gegevensgroepen, tabel-entiteiten en enumeraties zijn met dezelfde naam. Bijvoorbeeld gegevensgroep Nationaliteit bevat een tabel-entiteit Nationaliteit.
Om deze schema componenten uniek en herkenbaar te maken krijgt de naam van de schemacomponent voor een tabel de suffix "\_tabel" (bijvoorbeeld Nationaliteit_tabel) en krijgt de schemacomponent voor elke enumeratie de suffix "\_enum" (bijvoorbeeld Geslacht_enum).

**Comment by joeribekker** [comment]
Wellicht goed om onderscheid te maken tussen design keuzes voor intern gebruik en voor extern gebruik (leveranciers). Het is niet persé nodig dat leveranciers dit ook doen (ik zie de meerwaarde niet en hun codegen doet misschien iets anders), maar voor een consistente OAS vanuit VNG kan het wel nuttig zijn.

**Comment by fsamwel** [comment]
Volgens mij gaat het niet om een technische aanpassing, maar om woordgebruik. Niks meer dan dat. Dus daar waar "tabel-entiteit" is gebruikt in de design keuzes, heb ik dat nu veranderd naar "domeinwaarden". Schijnt de betere term te zijn. Heeft verder geen enkel effect op wat een developer moet doen.
De design keuzes zijn nu nog een projectdocument waarin de verschillende beslissingen kris-kras door elkaar staan. Uiteindelijk moeten we denk ik het document herordenen, een deel van de beslissingen uitwerken in de productvisie, en wellicht een onderscheid maken tussen ontwerpbeslissingen die effect hebben op developers en ontwerpbeslissingen die alleen effect hebben op het ontwerp van de api specs. Het grootste deel van de huidige beslissingen heeft op dat laatste betrekking.

**Comment by joeribekker** [comment]
Eens met Frank.

> Heeft verder geen enkel effect op wat een developer moet doen.

Behalve dit zinnetje 😄 Dit hangt helemaal af van hoe zwaar VNG de OAS (die leveranciers bouwen) wil valideren. Dat kan inhoudelijk zijn, of op structuur, of zelfs op naamgeving. In dat laatste geval heeft het **wel** effect op developers (en is het een last voor leveranciers).

**Comment by fsamwel** [comment]
Is het voor de interoperabiliteit nuttig om de OAS die leveranciers bouwen te valideren op naamgeving?
Die zie ik nog niet zo. Het zou denk ik moeten gaan om wat er werkelijk gestuurd wordt, niet om hoe dat in een applicatie is geïmplementeerd.

**Comment by CathyDingemanse** [comment]
Frank, eens.
