### ISSUE TITLE
Moet een INP meerdere partners kunnen hebben?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#36]
# Vraag

Op dit moment staat de OAS toe dat er meer dan 1 partner is van een INP. Klopt dit?

**Comment by Remkodehaas** [comment]
Je kan maar 1 actueel huwelijk hebben, lijkt mij (persoonlijke uitspraak).
Je kan wel meerdere partners hebben als je de historie mee telt. Zelfs met dezelfde persoon, nl. 1 actuele huwelijk en 1 in het verleden.
In RSGB komt de recursieve relatie 'heeft als partner' bij NATUURLIJK PERSOON (NP) voor [ingeschreven NP is een specialisatie van NP]. Daar kan iemand meerdere partners hebben. 
In LO GBA komt dit ook voor (zie pagina 155): kardinaliteit 0..N (bij categorie 5 Huwelijk/GPS)

en kennelijk komen polygame relaties voor in de GBA: [https://www.parool.nl/binnenland/nederland-telt-1374-polygame-huwelijken~a268479/](url) 

Vraag is of je dat in deze sprint wil mee nemen of in een later stadium

**Comment by joeribekker** [comment]
Helder. Er zit nu geen relatie informatie verwerkt in de link van "NP heeft als partner NP" (volgens laatst gegenereerde  OAS can Johan). Voor in de eerste opzet houd ik meerdere partners aan zonder context. Hier dient echter relatie informatie bij te komen (wordt nieuw issue).

**Comment by fsamwel** [comment]
De GET /ingeschrevennatuurlijkpersoon moet de actuele status van deze persoon teruggeven. Deze bevat dan geen historie (op bijna elke eigenschap van de persoon is er historie in de registratie). Is het dan nog steeds zo dat er tegelijkertijd meerdere partners kunnen zijn? Is in de definitie van partner een ex-partner ook een actueel gegeven?

**Comment by CathyDingemanse** [comment]
Antwoord Burgerzakenexpert op de vraag hoeveel actuele partners een ip kan hebben:

In het LO GBA staan alle huwelijken/partnerschappen (behalve de nietig verklaarde huwelijken, maar die hebben nooit bestaan) in de "actuele categorie". 
Met alle huwelijken/partnerschappen wordt bedoeld: 
- de huwelijken/partnerschappen die zijn gesloten en niet zijn ontbonden en 
- de huwelijken partnerschappen die wel zijn ontbonden, te herkennen aan een ingevulde datum ontbinding en reden ontbinding (overlijden, scheiding).
Er kan sprake zijn van meer dan een huwelijk dat niet is ontbonden. Bigamie bestaat dus idd.

We moeten dus kiezen wat wij onder actuele partner verstaan. Ik stel om:
- bij resource inp de relatie(s) op te nemen met partner(s) uit een niet ontbonden huwelijk/partnerschap - de partners uit ontbonden huwelijken en partnerschappen op te nemen in de resource partnerhistorie. 

Let op! Bij de aanduiding naamgebruik mag de naam van een partner uit een ontbonden huwelijk/partnerschap worden gebruikt als er geen actuele partner is!
