### ISSUE TITLE
De API spec gebruikt niet de standaard bestandsnaam

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/Bevragingen-ingeschreven-personen#38]
Volgens de [OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#document-structure) is het aangeraden om de API spec documenten `openapi.yaml` en/of `openapi.json` te noemen, in plaats van de huidige `BRPB1.0.yaml`

Concreet geven we dat bij de ZDS services invulling in de papieren [standaard](https://github.com/VNG-Realisatie/gemma-zaken/blob/8ea3b5a8539bcc7b36e09960c61940aba0d28ab4/standaard.md#beschikbaar-stellen-van-api-spec). Aanleiding hiertoe is de (generieke) [client](https://github.com/VNG-Realisatie/gemma-zds-client/blob/master/zds_client/client.py#L134) die op basis van een resource URL de API spec opvraagt die geserveerd wordt om vervolgens operaties op de API uit te kunnen voeren.

**Comment by fsamwel** [comment]
Sergei, is dit nu goed opgelost en kan dit issue gesloten worden?

**Comment by sergei-maertens** [comment]
Ziet er prima uit zo :+1:
