### ISSUE TITLE
Verblijfsplaats niet verplicht maar datumBeginGeldigheidVerblijfplaats wel

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#42]
# Impediment

`Verblijfsplaats` is niet verplicht maar `datumBeginGeldigheidVerblijfplaats` wel. Klinkt inconsistent.

**Comment by JohanBoer** [comment]
datum BeginGeldigheidVerblijfsplaats is nu niet verplicht gemaakt. Conform Design decision.
