### ISSUE TITLE
Geslachtsaanduiding is niet verplicht maar de enum bevat "onbekend"

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#43]
# Impediment

`Geslachtsaanduiding` in de OAS is niet verplicht maar de enum bevat "onbekend". Mij is onduidelijk wat het verschil is tussen een lege waarde (het attribuut is immers niet verplicht) en de waarde "onbekend".

**Comment by JohanBoer** [comment]
In het informatiemodel RSGB is dit element optioneel. Als ik het LO GBA er op nalees, Dan is voor ingeschreven personen rubriek gegevensgroep "04 Geslacht" met als element "Geslachtsaanduiding" verplicht. 

Volgens mij kunnen we de conclusie trekken dat op basis van het LO GBA 3.10 dit element verplicht is. Dat ga ik zo in het bericht doorvoeren. Ik leg de vraag neer bij Ellen en Remco. Ik kan de issue niet aan hen assignen, want ze staan niet in het lijstje.  

Vraag: Zou gezien het bovenstaande de geslachtsaanduiding niet verplicht moeten zijn (in EA Multiplicity -= 1)  en zo niet, waarom niet ?

**Comment by JohanBoer** [comment]
Het was mij even ontschoten, maar wij hebben in een design decision aangegeven dat bij een bevraging er geen verplichte properties zijn. Dat betekent dat "Geslachtsaanduiding" dus niet required is, maar ook dat elementen die dat nu nog wel zijn ook niet meer mogen zijn.

**Comment by joeribekker** [comment]
Oh, dat klinkt als onzinnig. Ik open dan een nieuw issue om deze design decision aan te passen.

**Comment by Remkodehaas** [comment]
In RSGB is attribuut Geslachtsaanduiding opgenomen bij NATUURLIJK PERSOON (NP). Het is niet verplicht daar omdat een NP ook een ANDER NP kan zijn.

Ik vind overigens dat het LO GBA lastig te lezen is over wat wel of niet verplicht is, aangezien er geen duidelijk overzicht is met kardinaliteiten, maar op grond van het overzicht op pagina 155 is het een verplicht gegeven voor een INGESCHREVEN NP.
