### ISSUE TITLE
Als ontwikkelaar wil ik verplichte attributen in het antwoord

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#45]
...zodat ik minimaal de verplichte gegevens terug krijg.

Ergo, anders is een valide antwoord, een leeg antwoord. Tevens is het vrij gebruikelijk om verplichte attributen op response niveau gelijk te houden aan die op (mogelijk) schrijf niveau (=1 definitie van een resource ~ Objecttype)

Betreft:
https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#de-response-heeft-geen-verplichte-properties
> **De response heeft geen verplichte properties**
> Alle properties in de response worden in de Open API Specificaties gedefinieerd als optioneel, ook wanneer de betreffende attributen in het informatiemodel verplicht zijn.
>
> *Ratio* De hoeveelheid businesslogica in interface beperken. Zorgen dat zoveel mogelijk antwoord gegeven kan worden, ook wanneer een verwachte property geen waarde heeft. Het alternatief, het opnemen van de reden van geen waarde (zoals StUF:noValue) is dan niet nodig, wat het gebruik van de API eenvoudiger maakt.

Wat van deze attributen getoond wordt aan een eventuele gebruikersinterface staat hier los van. Een consistente lees/schrijf interface is veel waardevoller voor een ontwikkelaar (we gooien immers een "State" -S van REST- over de lijn).

**Comment by fsamwel** [comment]
Het lastige is hier dat in registraties soms "verplichte" gegevens niet aanwezig zijn. Verplicht in RSGB betekent dat het gegeven (vanuit semantisch oogpunt) een waarde hoort te hebben. Maar de praktijk is soms weerbarstiger en een "verplicht" in de RSGB mag je niet 1-op-1 vertalen naar een technische verplicht.
In StUF hadden we psi:nil="true" en noValue om toch een verplicht veld leeg te kunnen laten. Voor onze API's willen we dat eenvoudiger houden. Dus als de registratie een verplicht gegeven echt niet heeft, zou dat tot een fout-response (statuscode 400 o.i.d.) leiden. Wil een client liever een foutmelding dan een onvolledig maar juist bericht?  Of wil je voor elk verplicht gegeven een xsi:nil achtige constructie?

Wat bedoel je met het verliezen van de "State" uit REST? Het gaat hier toch om het teruggeven van de actuele status van de resource?
Of een property verplicht is of niet maakt m.i. weinig uit hier, als deze een waarde heeft in de registratie van de provider, moet deze ook worden opgenomen in de response. Dat geldt toch ook voor niet-verplichte properties?

**Comment by JohanBoer** [comment]
Als je de actuele status van je Resource communiceert, dan geef je dus ook terug dat een verplicht element een null value heeft. Het is maar de vraag of je wilt communiceren waarom iets null is. 

Waar ik wel benieuwd naar ben is hoe je omgaat met een verplicht veld waarvoor je niet geauthoriseerd bent als afnemer. Als je in de API dat veld verplicht maakt, maar je mag die waarde niet zien, dan zou je in het geval van een null value dus niet de "State" van de resource terug krijgen. Je kan het veld echter niet weglaten. 

Volgens mij is dus het valide argument om alle elementen optioneel te maken, dat je vanuit de techniek geen restrictie wilt leggen op de authorisatie-structuur.

**Comment by dennisdewit81** [comment]
Ik sluit me aan bij de stellingname van Johan: alle elementen optioneel. Afhankelijk van gegevensbehoefte of autorisatie kun je niet stellen dat er altijd een bepaald element in het antwoord is opgenomen.

**Comment by fsamwel** [comment]
Conclusie: geen properties verplicht in het antwoord

**Comment by joeribekker** [comment]
Meestal geeft de issuer nog iets aan voordat hij gesloten wordt 😉 

Ik zie het niet veel, dat op basis van autorisaties attributen worden weggelaten. Lijkt me ook nogal verwarrend voor ontwikkelaars, waar ze precies vanuit kunnen gaan. Het is niet direct te zien via de OAS, maar je zou er iets over kunnen opnemen in descriptions en scopes.

Als het overigens gaat over "gegevensbehoefte" (zoiets als `?fields=`) zijn daar geen standaarden voor, en wordt er niets gezegd over dat `?fields=geslachtsnaam` bijvoorbeeld het verplichte `burgerservicenummer` attribuut moet teruggeven, ondanks dat er alleen om geslachtsnaam gevraagd wordt. Als dit gewenst is zou ik er een design keuze van maken.

Ik vind het geen halszaak, dus prima om de alle velden optioneel te maken in GET-requests.
