### ISSUE TITLE
Als teamlid wil ik dat issues middels Pull Requests worden gesloten

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#47]
...zodat duidelijk is waarom een issue gesloten wordt.

Nu is er een lijst met issues en wordt er af en toe een willekeurige set aan changes in de vorm van een nieuw OAS bestandje toegevoegd. Het is dan compleet onduidelijk welke wijzigingen zijn gedaan en waarom deze zijn gedaan. Ik kan echt de helft van de wijzigingen niet relateren aan bestaande issues...

**Comment by JohanBoer** [comment]
Snap ik. Ik werk nu naar eer en geweten op deze manier. Dit issue leidt niet tot changes, dus deze sluit ik zonder pull request.
