### ISSUE TITLE
Relatie informatie toevoegen

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Bevragingen-ingeschreven-personen#53]
Aan de hand van #36 is gebleken dat relatie informatie nodig is voor "NP heeft als partner NP". Denk dat dit voor alle relaties gaat gelden. Volgens hoort dit ook zo volgens het IM.

**Comment by fsamwel** [comment]
Bedoel je hiermee specifiek historische informatie (begin- en eind geldigheid, datum registratie)? Of zie je ook nog andere soort relatie-informatie?

Wanneer de relatie informatie alleen historie betreft hoeven we dat alleen op te nemen wanneer we willen dat deze historie ook wordt teruggegeven. Voor deze API willen we echter maar op een beperkte set eigenschappen historie en hebben we daarvoor specifieke resources gedefinieerd (zoals partnerhistorie). De gedachte daarachter is dat het overgrote deel van de gebruikers niet geïnteresseerd is in historie. Voor deze gebruikers moet de API zo eenvoudig (en snel) mogelijk zijn. En er dus op kunnen vertrouwen dat bijvoorbeeld de partner die teruggegeven wordt een actuele partner is.

**Comment by JohanBoer** [comment]
Zaken als de beschrijving van de relatie en de titel van de relatie worden wel opgenomen in het yaml bestand. Als bij een relatie daar geen sprake van is , dan is dat een fout in de UML en dus een specifiek issue.

**Comment by fsamwel** [comment]
@joeribekker kan je aangeven exact welke relatie informatie je mist?

**Comment by joeribekker** [comment]
Het gaat mij om context bij een relatie (API relaties mappen hier mooi op echte relaties). Prima dat een NP een kind heeft, maar is dat een biologisch kind of geadopteerd?

Als je historie hierin niet meeneemt (wat inderdaad vooral op relatie niveau ligt) is relatie informatie inderdaad beperkt. Vraag me dan wel af hoe jullie dan voor je zien hoe de API er uitziet om wel historische gegevens op te vragen. Mijn inziens zou dit dezelfde API danwel resource moeten zijn.

**Comment by Remkodehaas** [comment]
in het informatiemodel zit historie bij deze relatie. 

Wat wil je precies bevragen (t.a.v. Ouder-Kind-relatie) en waartoe? Is het onderscheid tussen biologisch of geadopteerd kind belangrijk voor deze Api?

Volgens mij zijn er allerlei varianten mogelijk: 
1.) je kan ouder zijn en niet het gezag hebben. 
2.) Een ouder (niet getrouwd of geregistreerd partnerschap) kan het kind later dan de geboortedatum erkennen, waardoor de datum van ontstaan van de ouder-kind-relatie niet overeenkomt met de geboortedatum, terwijl het geen adoptie is.
3.) etc...

Ik ben geen GBA- of BS-expert. De gemeenten kunnen aangeven wat nodig is.

**Comment by joeribekker** [comment]
Dit is issue is aangemaakt tijdens het Fieldlab, waarbij een testset van het GBA-V werd ingeladen. Bij het implementeren van een referentie implementatie op de OAS kwamen er specifieke issues naar boven, waaronder enkele relaties naar partners, kinderen, verblijfplaatsen die zonder historische informatie (wat nog niet in de OAS zat) onduidelijk zouden zijn. [Later is besloten om alleen actuele gegevens toe te voegen](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/issues/36#issuecomment-425844764)

> Wat wil je precies bevragen (t.a.v. Ouder-Kind-relatie) en waartoe? Is het onderscheid tussen biologisch of geadopteerd kind belangrijk voor deze Api?

Het voorbeeld was ongelukkig gekozen. Het is inderdaad ook geen attribuut in de testset GBA-V. Hoewel het nog steeds wellicht handiger is voor sommige relaties om informatie te bevatten, zoals het type partnerschap tussen personen, heb ik dit ticket dusdanig generiek ingeschoten dat de meerwaarde ontbreekt. Daarnaast ben ik ook geen IA.

Het issue is niet gedreven door een User Story, maar puur om de testset in te laden en wat er meer moest gebeuren. Voor de hand lag toen om deze (relatie)informatie toe te voegen om een werkbare situatie te creeeren.

Wat mij betreft mag het issue worden gesloten, en als de vraag vanuit gemeenten komt of iemand een consumer creeert op deze API wat tot nieuwe inzichten leidt, kan er een nieuw issue voor aangemaakt worden.

**Comment by fsamwel** [comment]
Bijvoorbeeld partnerschap, die eigenschappen van de (aard van de) relatie bevat, is inderdaad iets dat moest worden toegevoegd. Heeft Johan inmiddels gedaan.
