### ISSUE TITLE
Als gemeente... wil ik een functionele beschrijving van het koppelvlak

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#60]
...zodat ik weet wat ik hiermee kan bereiken, welke applicaties deze API moeten kunnen gebruiken, hoe dit past in mijn architectuur, wat ik aan infrastructuur moet organiseren, enz.

Doelgroepen:
- informatiemanager (gemeente)
- architect (gemeente)
- inkoper (gemeente)
- product manager (leverancier)

**Activiteiten:**
- per doelgroep informatiebehoefte bepalen
- bepalen publicatievorm (bijv. gemmaonline pagina's, pdf, GitHub md pagina's, ...
- afstemmen "sjabloon" met andere API projecten (Gemma zaken)
- schrijven functionele documentatie
- review

**Acceptatiecriteria**
*TODO: uitzoeken bij de doelgroepen wat precies hun informatiebehoefte is*
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie

**Comment by fsamwel** [comment]
Aanzet functionele specificaties gemaakt in pull request Ref. #68

Alternatieven:
- B.D.D. Gherkin specificaties, start hiertoe gemaakt in pull request Ref. #90
- functionele specificaties zoals in [zaken project](https://github.com/VNG-Realisatie/gemma-zaken/blob/8b6b1ce06835b500320eadccdd9081735362fc1f/docs/content/functioneel/zaken_api.md) worden gemaakt

**Comment by JohanBoer** [comment]
Dit is gerealiseerd. Er is een issue opgevoerd voor het reviewen /verifieren van de compleetheid en juistheid.
