### ISSUE TITLE
Als gemeente wil ik diensten kunnen verlenen aan personen zonder BSN

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/Bevragingen-ingeschreven-personen#62]
...zodat de leefwereld leidend wordt in plaats van de administratieve werkelijkheid.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Kan je aangeven op welke manier(en) de persoon moet kunnen worden gezocht/geselecteerd om de diensten te kunnen verlenen?

Wordt hier voldoende invulling aan gegeven wanneer men de persoon kan zoeken op naam en geboortedatum, of op verblijfsplaats? Of zijn er nog andere zoekcriteria gewenst?

**Comment by CathyDingemanse** [comment]
Dit project heeft als scope de basisgegevens. Personen zonder BSN zijn niet ingeschreven personen, dwz niet ingeschreven in een basisregistratie. In welke basisregistratie wil je hen dan zoeken? 
Houden wij registries bij van niet ingeschreven personen? Dat lijkt een contradictio in terminis, behalve als het om buitenlandse klanten gaat. 
In Den Haag worden deze buitenlandse klanten bijgehouden als onderdeel van andere basisregistraties, zoals de WOZ, en krijgt de gemeente gegevens uit de BRK en het Handelsregister, bijvoorbeeld in de hoedanigheid van bijv. zakelijk gerechtigde van een kadastrale onroerende zaak of eigenaar van of functionaris binnen een maatschappelijke activiteit etc.
Ontsluiting van deze resources vindt plaats in de daarvoor geplande standaardisatietrajecten. 
Daarnaast is het maar de vraag of je deze persoonsgegevens voor allerlei andere doelen mag opvragen dan waarvoor zij verzameld zijn.

**Comment by fsamwel** [comment]
De gevraagde functionaliteit wordt nu niet duidelijk. @ehotting wil je deze nog verduidelijken?

@CathyDingemanse wil je deze afvoeren als wontfix?

**Comment by CathyDingemanse** [comment]
SVP afvoeren als wontfix
