### ISSUE TITLE
To Append or not to Append ...

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Bevragingen-ingeschreven-personen#72]
# Impediment
Het gebruik van 'Append' om hiermee ook de Ouder-, Partner- en Kind-objecten direct in het resultaat terug te krijgen, leidt in het gebruik m.i. tot onnodige belasting aan provider-kant. Reken hierbij bijvoorbeeld ook mee dat deze mogelijkheid gecombineerd kan worden met het ontvangen van gegevens op een bepaalde peildatum. Dit alles in de wetenschap dat het hier gaat om (veelvuldige) bevragingen van ingeschreven personen; de BRP is immers een populaire bron.

_**NB.** Niet duidelijk wordt in hoeverre de 'Append' doorwerkt; hoe wordt omgegaan met de 'gerelateerde van de gerelateerde'. Blijft de levering hier dan beperkt tot de identificerende gegevens?_ 

Daarnaast gelden hier ook de privacy-regels; heeft de afnemer überhaupt wel recht tot het inzien van de gegevens van een gerelateerde persoon; valt deze binnen z'n doelbinding? Andere vraag is of het gebruik van de 'Append' zelf afgeschermd kan worden; per afnemer aan te geven wel/niet? Zoja, waar kunnen dit soort autorisaties straks worden ingeregeld? Komt hiervoor een Autorisatie-voorziening binnen NLX en wat is het bereik hiervan?

De mogelijkheid van 'eager loading' is bovendien erg verleidelijk in het gebruik. Ongeacht of deze gegevens in het proces nodig zijn, is het wel 'makkelijk' om deze direct op te vragen. Ongewenst gebruik ligt op de loer, legt groeter nadruk op logging&handhaving van de privacy-regels.  

Mijn advies is om de implementatie op dit punt eenvoudig te houden en de verleiding tot ongewenst gebruik te voorkomen door de 'Expand' niet aan te bieden en alleen 'lazy loading' van gerelateerden toe te passen. Als afnemer ontvang je (voor zover geautoriseerd) alleen de identificerende gegevens van een gerelateerde. Indien de detailgegevens van een gerelateerde noodzakelijk zijn voor de afhandeling van een taak of proces, dan de API voor deze gerelateerde ook aan te roepen.  

[assign aan ..., voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by JohanBoer** [comment]
Ik vermoed dat jouw feedback op het toepassen van de "expand"- parameter betrekking heeft waarmee aangegeven kan worden dat de gegevens van de ouders, kinderen of partners embedded kan worden geretourneerd. Tot nu toe is er in dit traject nog niets gezegd over het "appenden" van andere API's.

**Comment by gertjanvanderkooij** [comment]
> 
> 
> Ik vermoed dat jouw feedback op het toepassen van de "expand"- parameter betrekking heeft waarmee aangegeven kan worden dat de gegevens van de ouders, kinderen of partners embedded kan worden geretourneerd. Tot nu toe is er in dit traject nog niets gezegd over het "appenden" van andere API's.

Correct!

**Comment by fsamwel** [comment]
> NB. Niet duidelijk wordt in hoeverre de 'Append' doorwerkt; hoe wordt omgegaan met de 'gerelateerde van de gerelateerde'. Blijft de levering hier dan beperkt tot de identificerende gegevens?

Hiervoor is er een beslissing genomen: [er kan maar 1 niveau diep worden embed](
https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#relaties-kunnen-maximaal-%C3%A9%C3%A9n-niveau-diep-worden-embed).

**Comment by fsamwel** [comment]
naar mijn idee moeten we ook anders denken over de relaties van personen in de api/resource. zie #92.

**Comment by dennisdewit81** [comment]
Ik ben voorstander van enkel de relaties en de identificerende gegevens van de gerelateerde terug te geven (dan nog moet je nadenken over wat de identificerende gegevens zijn) in een antwoord. Ik vind dat we af moeten van het idee dat we beter in 1 API-call alles op kunnen halen wat we nodig hebben.
'Alles' is namelijk toch voor iedere consumer/afnemer verschillend. Elementaire API's zorgen ervoor dat via een reeks aanroepen van beknopte API's je als afnemer altijd de hele informatiebehoefte in kan vullen. Als de performance in orde is dan maakt een extra API-call niets uit.

M.a.w. 'not to expand'!

**Comment by fsamwel** [comment]
Zie #92. Er is wel de functionele wens om partnerschap, ouder en kindrelaties direct bij de persoon te kunnen krijgen, want dit zijn eigenlijk gegevens van de persoon zelf.
Reisdocumenten kunnen niet worden embed.
