### ISSUE TITLE
Zoekfunctionaliteit en Pagineren ...

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Bevragingen-ingeschreven-personen#73]
# Impediment
In de functionele specificaties lees ik geen inperkingen op het gebruik van het zoeken op eigenschappen van een persoon. Ik lees wel iets over het beperken van het aantal zoekresultaten per zoekvraag in combinatie met de mogelijkheid tot pagineren. 

Dit zet de deur wagenwijd open om te gaan 'rechercheren' ('ik zoek iets, maar weet niet precies wat') of de bron via de Bevraging-API 'leeg te trekken'? Lijkt me beide ongewenst in het geval van het bevragen van ingeschreven personen. 

Dit nog afgezien van eventuele performance-vraagstukken; zeker als ik lees dat 'Standaard alle attributen van een persoon in het antwoord worden terug gegeven' en ook de toepassing van de 'Append' mogelijk lijkt.  

In plaats hiervan zou ik volgende willen voorstellen:
1) Indien het aantal zoekresultaten de limiet overschrijdt, **geen** zoekresultaten terug geven maar de afnemer dwingen om gerichtere zoekcriteria op te geven.
2) De toepassing van zoekcriteria te sturen door hier bedrijfsregels op te zetten; alleen zoeken op 'Ja&' niet toestaan. Dit bv. altijd te combineren met een geboortedatum of postcode/huisnummer.    
3) De mogelijkheid van Pagineren niet te ondersteunen.   

Dit alles met in het achterhoofd dat dit een Bevraging-API betreft gericht op het ondersteunen van een afnemers bij het uitvoeren van een specifieke taak. En dit geen 'Verzamel-API' of 'Rechercheer'-API is. Als bv. aan deze laatste behoefte bestaat bij beperkt aantal afnemers, dan zou ik hiervoor een andere API maken. Houd de Bevraging-API zo simpel en toegepast mogelijk. 

**NB.** Zelfde vraagstuk hebben we ondervonden bij Operatie BRP. Indien afnemers behoefte hebben aan massale levering van persoonsgegevens, dan deze te leveren via andere methode dan deze bevraging-API (bv. selectie).

**Comment by fsamwel** [comment]
Wat zou een redelijk aantal zijn als maximum aantal zoekresultaten voor er een fout wordt teruggegeven?

**Comment by gertjanvanderkooij** [comment]
Als we voor de API (en de keten) gericht zoeken van Personen willen afdwingen, dan standaardinstelling laag houden (10, max 20?). 

Per afnemer in te stellen, zodat voor afnemers met een specifieke taak of die in hun proces/taak over onvoldoende identificerende gegevens beschikken een hoger aantal kan worden ingesteld.

In geval van Bewoning ligt deze grens hoger; hoeveel na te vragen bij gemeenten. Deze grens apart in te stellen.

Ik las dat de combinatie van Postcode/Huisnummer en Geboortedatum niet is toegestaan? Dit maakt zoeken naar een bepaalde persoon op een bepaald adres (studentenhuizen etc) gerichter.

**Comment by CathyDingemanse** [comment]
> Als we voor de API (en de keten) gericht zoeken van Personen willen afdwingen, dan standaardinstelling laag houden (10, max 20?).
> 
> Per afnemer in te stellen, zodat voor afnemers met een specifieke taak of die in hun proces/taak over onvoldoende identificerende gegevens beschikken een hoger aantal kan worden ingesteld.
> 
Bedoel je per binnengemeentelijke afnemer instellen of zoeken met de autorisatie van de gemeente als afnemer? Voor deze API wordt altijd met de algemene gemeentelijke autorisatie gezocht, en moet daarmee alle gemeentelijke processen bedienen (uiteraard binnen de functionele scope van deze API). Uitgangspunt is ook dat een persoon (of een kleine groep personen) wel gevonden moet kunnen worden, ook als je zoals jij al aangeeft over minder identificerende gegevens beschikt. Dan lijkt mij 10-20 resultaten aan de lage kant.

**Comment by CathyDingemanse** [comment]
> Ik las dat de combinatie van Postcode/Huisnummer en Geboortedatum niet is toegestaan? Dit maakt zoeken naar een bepaalde persoon op een bepaald adres (studentenhuizen etc) gerichter.

Eens, dit moeten we nog eens adresseren.

**Comment by gertjanvanderkooij** [comment]
> Bedoel je per binnengemeentelijke afnemer instellen of zoeken met de autorisatie van de gemeente als afnemer? Voor deze API wordt altijd met de algemene gemeentelijke autorisatie gezocht, en moet daarmee alle gemeentelijke processen bedienen (uiteraard binnen de functionele scope van deze API). Uitgangspunt is ook dat een persoon (of een kleine groep personen) wel gevonden moet kunnen worden, ook als je zoals jij al aangeeft over minder identificerende gegevens beschikt. Dan lijkt mij 10-20 resultaten aan de lage kant. Ik denk eerder aan een aantal dat geen zinvolle lijst meer oplevert die je als gebruiker ook echt gaat doorspitten. 100, iets meer?

Op niveau van de 'Gemeente als afnemer'; binnen de poorten van de gemeenten verdere afhandeling naar verschillende binnengemeentelijke afnemers (waaronder 2e autorisatiefilter). Als men voor een bepaald proces over minder identificerende gegevens beschikt, dan is 10-20 wellicht aan de krappe kant. Als we het principe van gericht zoeken willen nastreven lijkt 100 mij wel erg ruim; in die zin zou ik 'm liever krap houden dan te veel openzetten. Behalve voor bewoning omdat die situatie zich in de praktijk voor kan doen. 

Grens hoeft nu nog niet hard bepaald te worden; als we voorgesteld principe implementeren kunnen we ons later buigen over de exacte waarden. Deze op basis van bv. logging van het feitelijk gebruik dan desgewenst verhogen/verlagen.

**Comment by dennisdewit81** [comment]
Lijkt me goed om het maximaal aantal zoekresultaten in ieder geval geen onderdeel meer uit te laten maken van de vraag/call. Goed voorstel om de exacte aantallen later nog te kunnen finetunen en voor nu met een bepaald aantal te gaan werken.

**Comment by CathyDingemanse** [comment]
Paginering:
Ik heb nog geen vraag gehad van een afnemer naar paginering. Ik stel voor om dit in de eerste versie niet te doen, maar pas te implementeren als deze behoefte wordt uitgesproken en gemotiveerd door een afnemer. 

Max aantal resultaten: 
Laten aansturen door de consumer: sowieso niet aan beginnen.
Maximum aantal definieren voor een provider: dit is een implementatie issue, want heeft te maken met hoeveel last een provider krijgt van een te ruim gedefinieerde zoekvraag. Moeten we dit eigenlijk wel binnen de scope van standaard definieren? Weten wij van tevoren dan precies waar een provider last van krijgt? Ik wil eigenlijk geen aannames doen over waar een provider als dan niet last van krijgt. Dat kan ik ook niet, want dat is afhankelijk van de implementatie van de provider. 
Hoe erg is het om dit aan de provider te laten? Het betreft een waarschuwing of een foutmelding: het antwoord op jouw vraag is groter dan het maximum aantal, maar je krijgt maar x resultaten, of je krijgt helemaal niks.
Ik stel voor om dit helemaal aan de provider te laten.

**Comment by fsamwel** [comment]
> Het betreft een waarschuwing of een foutmelding: het antwoord op jouw vraag is groter dan het maximum aantal, maar je krijgt maar x resultaten, of je krijgt helemaal niks.
Moeten we in de API standaard wel kiezen tussen de twee? (ik denk van wel)
- waarschuwing (in de response header "warning") en beperkt aantal resultaten teruggeven
- foutmelding en niks teruggeven

**Comment by fsamwel** [comment]
Besproken in overleg 23 november. Beslissing:
* We doen geen paginering.
* API moet foutmelding geven wanneer er teveel resultaten zijn op de vraag. De gebruiker krijgt dan dus geen enkel resultaat terug, alleen de foutmelding (http status 4xx).
* Wij stellen in standaard niet wat het maximum aantal resultaten is. Dat mag de provider bepalen en zo nodig fine tunen op basis van daadwerkelijk gebruik.

**Comment by fsamwel** [comment]
> Ik las dat de combinatie van Postcode/Huisnummer en Geboortedatum niet is toegestaan? Dit maakt zoeken naar een bepaalde persoon op een bepaald adres (studentenhuizen etc) gerichter.

Beslissing (23 november):
We verbieden niet verschillende combinaties van zoekparameters. Wel worden minimale combinaties verplicht.
Er moet worden gezocht met minimaal:
* OF geslachtsnaam + geboortedatum
* OF postcode + huisnummer
* OF gemeentevaninschrijving + naamOpenbareRuimte + huisnummer
* OF nummeraanduiding

Wanneer aan de conditie is voldaan dat ten minste één van de genoemde minimale parameters gebruikt is, mag daar bovenop elke andere gedefinieerde zoekparameter gebruikt worden.
Hiermee wordt het dus mogelijk te zoeken op postcode + huisnummer + geboortedatum

De zoekparameter woonplaatsnaam wordt vervangen door de zoekparameter gemeentevaninschrijving (die al was gedefinieerd). M.a.w. zoekparameter woonplaatsnaam vervalt.

Gemeentevaninschrijving moet (in het antwoord) zitten in de groep verblijfplaats. Dat is in LO GBA namelijk element 9.10 uit categorie 08/58 Verblijfplaats. @JohanBoer: dat geldt denk ik ook voor verblijf buitenland. Er zitten in categorie 08/58 Verblijfplaats veel meer elementen dan nu in de api in verblijfplaats is gedefinieerd. Dit moeten denk ik worden toegevoegd. Kan je dat controleren en checken bij Remko hoe dat in zijn model zit?

**Comment by gertjanvanderkooij** [comment]
>     * nummeraanduiding

Om verwarring te voorkomen is besloten dit identificatiecodeNummeraanduiding te noemen.

**Comment by JohanBoer** [comment]
Voor nu de genoteerde aanpassingen gedaan. Op categorie 05/58 moet een analyse plaatsvinden die ik nu nog niet heb doorgevoerd.

**Comment by JohanBoer** [comment]
Alles is doorgvoerd zoals hier besproken
