### ISSUE TITLE
Hoe omgaan met in onderzoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#74]
Er is nu nog geen attribuut in onderzoek opgenomen in de API-specificaties.

Hoe hiermee omgaan?

N.a.v. https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/issues/67#issuecomment-432642760

**Comment by gertjanvanderkooij** [comment]
De GBA kent een fijnmazige wijze van het in onderzoek nemen van gegevens; zie hiervoor LO GBA par. 3.22. 

Voor de verstrekking van de onderzoek-(en procedure-)gegevens verwijs ik naar LO GBA par. 5.4.3.1 en 5.4.6.

Indien in geval van en zoekvraag of bewoningvraag slechts een beperkt deel van de persoonsgegevens als resultaat wordt terug gegeven **en** één van de niet geleverde gegevens is in onderzoek, dan zou ik in het resultaat een aparte (afgeleide) onderzoek-indicator opnemen die aangeeft dat één van de gegevens van betreffende persoon in onderzoek is. Dit alleen in geval van een lopend onderzoek. 

De afnemer kan dan de details van de persoon opvragen om in te zien welke gegevens in onderzoek staan en te beoordelen of dit van invloed is voor verdere afhandeling van diens proces/taak. 

Indien er persoonsgegevens in onderzoek staan waarvoor de afnemer niet is geautoriseerd, dan de afgeleide onderzoek-indicator niet vullen.

**Comment by gertjanvanderkooij** [comment]
> 
> 
> Technisch gezien hebben we dat in de vorige bevraging ingevuld door voor ieder element of gegevensgroep die mogelijk in onderzoek kan zijn een boolean op te nemen. Complicatie daarbij is dat als slechts een deel van de elementen wordt gevraagd ook alleen het corresponderende deel van de Ï "Inonderzoek" -booleans geleverd moet worden.
> De aparte (afgeleide) inonderzoek-indicator zoals die door GertJan beschreven wordt zou hier aan toegevoegd kunnen worden om het aan te geven als er gegevens in onderzoek zijn die niet in het geretourneerde resultaat zitten.

Toevoegen: "... en waarvoor de afnemer wel is geautoriseerd".

**Comment by fsamwel** [comment]
Gegevensgroep inOnderzoek wordt toegevoegd met daarin alle attributen van de persoon die in onderzoek kunnen zijn als boolean.
Hoe gaan we hier om met gegevensgroepen? Moeten we uitzoeken in LO GBA.
Hoe gaan we hier om met relaties? In RSGB-bevragingen 1.0 was er geen inOnderzoek geïmplementeerd op relaties. Extra check in LO GBA of dit terecht is.
Mocht inOnderzoek ook voor een relatie relevant zijn, dan wordt de relatie als attribuut opgenomen in de inOnderzoek-gegevensgroep.

Daarnaast moet dit onderwerp besproken worden in de functionele specificaties.

**Comment by fsamwel** [comment]
Opmerking Maarten vd Broek: In bg0310 zijn er minder elementen mogelijk in inOnderzoek dan nu in api is gedefinieerd.
We moeten dus wellicht controleren of we nu niet teveel attributen hebben opgenomen in de gegevensgroep inOnderzoek.

**Comment by JohanBoer** [comment]
> Opmerking Maarten vd Broek: In bg0310 zijn er minder elementen mogelijk in inOnderzoek dan nu in api is gedefinieerd.

Ik heb nu alle individuele elementen binnen een gegevensgroep opgenomen. Maarten's pleidooi was dat een hele gegevensgroep in onderzoek is of niet. Als dit onderschreven wordt kan ik dit vrij eenvoudig aanpassen.

**Comment by CathyDingemanse** [comment]
> Technisch gezien hebben we dat in de vorige bevraging ingevuld door voor ieder element of gegevensgroep die mogelijk in onderzoek kan zijn een boolean op te nemen. Complicatie daarbij is dat als slechts een deel van de elementen wordt gevraagd ook alleen het corresponderende deel van de Ï "Inonderzoek" -booleans geleverd moet worden.
> De aparte (afgeleide) inonderzoek-indicator zoals die door GertJan beschreven wordt zou hier aan toegevoegd kunnen worden om het aan te geven als er gegevens in onderzoek zijn die niet in het geretourneerde resultaat zitten.

Waarom wil je dat dan weten? Een onderzoeksindicator over gegevens die je niet gevraagd hebt of niet (mag) krijgen, is i.g.g. geen businesswens, maar maakt e.e.a. wel compexer. Ik zou het niet doen.

**Comment by CathyDingemanse** [comment]
> > Opmerking Maarten vd Broek: In bg0310 zijn er minder elementen mogelijk in inOnderzoek dan nu in api is gedefinieerd.
> 
> Ik heb nu alle individuele elementen binnen een gegevensgroep opgenomen. Maarten's pleidooi was dat een hele gegevensgroep in onderzoek is of niet. Als dit onderschreven wordt kan ik dit vrij eenvoudig aanpassen.

Wat in StUFbg is gedefinieerd is geen uitgangspunt voor deze API. Het aparte opnemen van de gegevensgroep onderzoek is gedaan met complexiteitsreductie als doel (anders komt het overal in de resource terug). Dat de afnemers vervolgens _exact_ wordt geinformeerd over wat er precies in onderzoek is, is vanuit gebruikersperspectief zeer gewenst.

**Comment by gertjanvanderkooij** [comment]
> Indien in geval van en zoekvraag of bewoningvraag slechts een beperkt deel van de persoonsgegevens als resultaat wordt terug gegeven **en** één van de niet geleverde gegevens is in onderzoek, dan zou ik in het resultaat een aparte (afgeleide) onderzoek-indicator opnemen die aangeeft dat één van de gegevens van betreffende persoon in onderzoek is. Dit alleen in geval van een lopend onderzoek.

Mijn afgeleide indicator is alleen bedoeld voor de situatie dat:
1) Er besloten wordt dat we bij 'Zoeken'/'Medebewoning' een beperkte resultaatset terug geven
2) Één van de elementen waarvoor de afnemer geautoriseerd is, maar niet terugkomt in bovenbedoelde beperkte resultaatset actief in onderzoek staat. 

Als je de nadere details details zou opvragen, dan krijg je de onderzoekindicator wel te zien. De afgeleide indicator zorgt er in dat geval voor dat je als afnemer direct na de Zoek- cq. Medebewoner-vraag op wordt geattendeerd.

**Comment by JohanBoer** [comment]
> Wat in StUFbg is gedefinieerd is geen uitgangspunt voor deze API. Het aparte opnemen van de gegevensgroep onderzoek is gedaan met complexiteitsreductie als doel (anders komt het overal in de resource terug). Dat de afnemers vervolgens _exact_ wordt geinformeerd over wat er precies in onderzoek is, is vanuit gebruikersperspectief zeer gewenst.

Duidelijk verhaal, ik kon niet achterhalen wat nu de gebruikerswens is. Nu wel. Ik laat de gedetailleerde inOnderzoek indicatoren in stand. .

**Comment by fsamwel** [comment]
> Dat de afnemers vervolgens exact wordt geinformeerd over wat er precies in onderzoek is, is vanuit gebruikersperspectief zeer gewenst.

Mogen we hieruit concluderen dat in onderzoek altijd op attribuut-niveau (zoals voornamen of huisnummer) wordt aangegeven, niet op groep van attributen (zoals naam of verblijfplaats)?

**Comment by fsamwel** [comment]
Beslissing (23 november): 
* Als een hele categorie (gegevensgroep) in onderzoek is, wordt in het antwoord elk attribuut van die categorie als inOnderzoek gegeven.
* A-nummer moet uit inOnderzoek worden gehaald
