### ISSUE TITLE
Hoe omgaan met indicatie geheim

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#75]
Hoe gaan we in z'n algemeenheid om met personen die een indicatie geheimhouding hebben?

N.a.v. https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/issues/67#issuecomment-432642760

**Comment by gertjanvanderkooij** [comment]
Als deze API alleen bedoeld is voor gebruik door gemeenten dan kan je dat zo doen; deze 'afnemer' is immers geautoriseerd voor het stellen van adhoc-vragen voor personen met geheimhouding. Als ik het autroisatiebesluit quickscan zelfs voor alle taken. Indien het binnengemeentelijk gebruik ook anders is/wordt qua taken (mmm, hier zou dan besluit aan ten grondslag moeten liggen ... en of dit in alle gevallen zo is, laat zich raden ...), is er een mechanisme nodig dat voorkomt dat abusievelijk gegevens van personen met geheimhouding kunnen worden opgevraagd.

Is het de idee dat ook andere partijen dan gemeenten gebruik gaan maken van deze API, dan moet de toegang tot Personen met de indicatie Geheim wel centraal geregeld kunnen worden en niet binnen de grenzen van een partij/afnemer  waaraan geleverd wordt ... dan heb je immers al geleverd en dat was nu net niet de bedoeling. 

Zie ook LO GBA III.2.9 Adhoc vragen:
_"Bij het beantwoorden van de vraag speelt de Indicatie geheim op een PL een belangrijke rol.
Door deze indicatie kan de verstrekking van persoonsgegevens aan bepaalde groepen
afnemers worden tegengegaan. De groepen afnemers waarvoor dit van toepassing is, zijn
geautoriseerd voor het stellen van ad hoc vragen, maar hebben de Indicatie geheimhouding
aan staan in hun autorisatietabelregel."_

**Comment by ehotting** [comment]
Dit kan goed door binnen de API 'scopes' (jargon uit OAuth2) te definiëren die worden aangevraagd in de request, en aan de provider kant te checken of de ID deze scope mag aanvragen. Kunst is om het aantal scopes te beperken (beheerslast) maar toch alle benodigd onderscheid in autorisaties te kunnen maken.

**Comment by CathyDingemanse** [comment]
De gemeente (en LV) mag ingeval van indicatie geheim geheim geen persoonsgegevens doorgeven aan:

de Stichting Interkerkelijke Ledenadministratie (SILA);
organisaties die gezondheidszorg verlenen aan patiënten in een instelling;
organisaties die gerechtelijke werkzaamheden uitvoeren.
organisaties waaraan een gemeente persoonsgegevens zou willen geven op basis van een gemeentelijke verordening. Bijvoorbeeld een sportvereniging of een goed doel zoals het Rode Kruis. 
De geheimhouding geldt voor alle gegevens uit de BRP.

Voor binnengemeentelijke afnemers geldt dit niet. Bijna alle afnemers hebben bovendien het recht dit gegeven te gebruiken zodat men zich bij het gebruik bewust is van de geheimhoudig. Binnen gemeente Den Haag gaan er in de meeste user interfaces extra toeters en bellen af om hier op de aandacht te vestigen. 

Mijn conclusie is dat het al dan niet verstrekking van persoonsgegevens gewoon onderdeel uit maakt van de autorisatiefilters van de betreffende afnemersgroepen. Hiervoor hoeven geen aparte maatregelen te worden genomen.

**Comment by gertjanvanderkooij** [comment]
OK!

Terugkomend op mijn opmerking:
> Is het de idee dat ook andere partijen dan gemeenten gebruik gaan maken van deze API, dan moet de toegang tot Personen met de indicatie Geheim wel centraal geregeld kunnen worden en niet binnen de grenzen van een partij/afnemer waaraan geleverd wordt ... dan heb je immers al geleverd en dat was nu net niet de bedoeling.

Naar ik nu begrijp is de API bestemd voor gebruik door binnengemeentelijke afnemers. Indien ook andere partijen aansluiten zijn er mogelijkheden om de boel af te schermen. 


> Mijn conclusie is dat het al dan niet verstrekking van persoonsgegevens gewoon onderdeel uit maakt van de autorisatiefilters van de betreffende afnemersgroepen. Hiervoor hoeven geen aparte maatregelen te worden genomen.

@CathyDingemanse; Wat bedoel je hier met 'autorisatiefilters van de betreffende afnemersgroepen'? Onderdeel van de inrichting van NLX cq. de API?

**Comment by CathyDingemanse** [comment]
De provider die de persoonsgegevens verstrekt is verantwoordelijk voor het verstrekken van gegevens conform de rechten van de bevrager op basis van doelbinding. 
De doelbinding die je hebt om een gegeven te gebruiken leidt tot een set van rechten. Deze rechten krijgen hun weerslag in een autorisatieprofiel. Verschillende doelbindingen die horen bij het uitvoeren van een wettelijke taak kunnen dus (toevallig!) leiden tot eenzelfde autorisatieprofiel.
Dit autorisatieprofiel werkt als een filter op de resource, en "filtert" gegevens uit de resource die de gerechtigde niet mag zien.

**Comment by fsamwel** [comment]
Besproken in overleg 23 november.
indicatie geheim zit (al) als attribuut in het antwoord. Autorisatie hiervoor hoeft verder niet in de API beschreven te worden.
