### ISSUE TITLE
Als gemeente wil ik ingeschreven personen kunnen zoeken op postcode en huisnummer van het verblijfsadres

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#8]
zodat ik de gegevens van een persoon kan vinden..

**Acceptatiecriteria**
- [x] Het is mogelijk te kiezen om ook of juist geen overleden personen terug te krijgen
- [x] Het is mogelijk te zoeken (filteren) op de volgende eigenschappen van de persoon:
       * postcode
       * huisnummer
       * huisletter
       * huisnummertoevoeging
       * locatieaanduiding
       * periode (van, tot en met)

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Hoe moet de parameter periode werken?

**Comment by fsamwel** [comment]
deze userstorie wordt geïmplementeerd met een endpoint /bewoners

**Comment by JohanBoer** [comment]
> * Het is mogelijk te zoeken (filteren) op de volgende eigenschappen van de persoon:
>   * postcode
>   * huisnummer
>   * huisletter
>   * huisnummertoevoeging
>   * locatieaanduiding
>   * periode (van, tot en met)

Bovenstaande eigenschappen zijn geen eigensschappen van een persoon, maar van een verblijfsplaats. Hier wordt dus een verplijsplaats gezocht en embedded worden alle actuele bewoners geretourneerd. 
De endpoint is nu /bewoning genoemd.

**Comment by fsamwel** [comment]
Wat is het effect voor onze keuze voor zoeken bewoners op de functionele wens om wel of juist geen overleden personen terug te krijgen? Krijg je nu altijd bij /bewoners (of /bewoning ?) alleen levende personen en bij /bewonershistorie (of bewoningshistorie ?) altijd (voormalige) bewoners ook als ze inmiddels overleden zijn?

**Comment by JohanBoer** [comment]
Ik heb inmiddels de queryparameter "InclusiefoverledenPersonen"toegevoegd, zodat je expliciet aan kan geven of de overleden personen opgenomen moeten worden in het resultaat. Deze userstory heeft stevige raakvlakken met  #9 en #17 . 
Het zoeken op een adres (actueel of in het verleden) levert in mijn beleving altijd bewoners. (een bewoner is een ingeschreven persoon + de ingangsdatum en de einddatum van de relatie "Ingeschrevenop" (verblijfsadres). Vraag is of je in de resource "bewoners" dehele doopceel van de ingeschrevenpersoon opneemt of alleen enkele gegevens en een verwijzing naar de ingeschrevennatuurlijkpersoon. 
Ik heb vooralsnog voor het laatste gekozen.

**Comment by joeribekker** [comment]
Iets RESTfuller zou zijn: `?overlijden=null`. Dit betekent namelijk dat het (groeps)attribuut `overlijden` niet is voorzien van data. Hiervoor hoeft dan geen parameter verzonnen te worden.

Het is wel de omgekeerde variant: Standaard krijg je iedereen, en met filteren krijg je alleen mensen die nog niet overleden zijn. Dit is wel consistenter met de andere filters. 

Als ik in Johans versie namelijk zoek op een BSN, en ik vind niets. Dan moet ik daarna zoeken op BSN + InclusiefOverledenPersonen, om te controleren of het wellicht een overleden persoon betreft. Geldt uiteraard ook voor zoeken op achternaam, etc..

Ik zou zo min mogelijk aannames doen op de "collection" (zoals er van uit gaan dat mensen moeten leven). Ik beschik echter niet over de User Stories die aangeven hoe de API het meest gebruikt zou worden.

**Comment by CathyDingemanse** [comment]
Ik stel voor een nieuwe issue aan te maken voor zoeken inclusief/exclusief overleden personen, en dit issue te sluiten, omdat de overledenpersonne discussie voor meer zoekpaden relevant is.

**Comment by CathyDingemanse** [comment]
Voor zoeken op de inschrijving geldt: voor de inschrijving op een verblijfplaats eindigt niet als de persoon overlijdt. Het komt daarom vaak voor dat overleden personen worden geretourneerd bij opgave van een nummeraanduiding. Dit is bijna nooit de bedoeling :-). Niet alle gebruikers hebben dit in de gaten, en eea is vaak ook geen onderdeel van de testset. M.a.w. het risico op genante en zeer pijnlijke fouten is aanwezig. (Heb ik overigens zelf ook ooit heb gemaakt bij realisatie van een verhuisapp waar je medebewoners kon meeverhuizen. Gelukkig kwamen we er net op tijd achter).

Een andere optie is om de inschrijving wel te laten eindigen op het moment van overlijden (wat natuurlijk ook echt zo is, omdat je na overlijden in een urn of op het kerkhof verblijft). Dan hoef je voor het veel gebruikte zoeken naar actuele bewoners iig niet  ?overlijden=null mee te geven. Echter, dat moet dan nog steeds wel bij het zoeken van inp op persoonskenmerken (geslachtsnaam, voornamen, geboortedatum etc.), dus dat lijkt geen generieke oplossing.  

Ik neig naar een oplossing die het meest voorkomende gebruik faciliteert zonder specifieke kennis te hebben van het domein (en de documentatie (?overlijden=null) tot in de puntjes te hebben bestudeerd). Dat is dan de oplossing van Johan.

**Comment by JohnRooijakkers** [comment]
Hoewel het vanuit de BRP gezien correct is dat een overleden persoon nog steeds "ingeschreven" staat op het laatste adres, is het in mijn ogen niet gewenst om deze persoon nog steeds als "bewoner" te beschouwen. Het is dus de vraag of we bij een adres de "ingeschreven" personen willen zien of de "bewoners". Ik denk dat de meeste gebuikers de bewoners willen zien (op dit moment of op een peildatum).

**Comment by JohanBoer** [comment]
Voortschrijdend inzicht van de afgelopen  weken heeft ons er toe gebracht om de actuele bevraging te implementeren op het endpoint _/ingeschrevenpersonen_  de actuele verblijfplaats is als gegevengorpe gemodelleerd en dus een eigenschap van de ingeschreven persoon. Daarmee kunnen de bovengenoemde elementen als zoek-parameter op dit enpoint worden gebruikt. 

De bevraging op verblijfplaatshistorie (dus de parameters "periode( van, Tot en met)  wordt op een separaat endpoint gerealiseerd.

**Comment by JohanBoer** [comment]
Inmiddels gerealiseerd zoals in de laatste comment beschreven.
