### ISSUE TITLE
Wil je geldigheidsdatums van verblijfplaats in actuele bevraging krijgen?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#80]
Willen we dat in het antwoord op de actuele persoon ook de geldigvan en geldogtotenmet worden opgenomen?
M.n. voor verblijfplaats en verblijfstitel.

**Comment by fsamwel** [comment]
Melvin geeft aan dat dit handig is. dus wel doen (is al gedaan in huidige open api specificaties

**Comment by CathyDingemanse** [comment]
OK

**Comment by fsamwel** [comment]
Mee eens. Je moet niet willen goochelen met waarden die we teruggeven, dus gewoon teruggeven zoals het in de registratie staat. En dus in je voorbeeld 'geldigTotEnMet' = 30-4-2018.

**Comment by fsamwel** [comment]
Wanneer we wel geldigheid opgeven (in de actueel resource) voor verblijfplaats en verblijfstitel, willen we dat dan niet ook voor de resource als geheel?

**Comment by fsamwel** [comment]
> Wanneer we wel geldigheid opgeven (in de actueel resource) voor verblijfplaats en verblijfstitel, willen we dat dan niet ook voor de resource als geheel?

Besproken in overleg 23 november: Nee, alleen op verblijfplaats en verblijfstitel.

Is zo ook al verwerkt in de api specificaties
