### ISSUE TITLE
Naamgeving van attributen van een gegevensgroep als query parameter

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#84]
In het Gemma-zaken project is een  [ontwerpbeslissing](https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/content/developers/design-keuzes.md#relaties-aangeven-in-query-parameters) genomen:
> Om relaties zowel naar een andere resource (zoals status) als naar een genest attribuut (zoals kenmerken) te gebruiken binnen query parameters, wordt de __ (dubbele underscore) gebruikt tussen de attribuutnamen.

Ten behoeve van consistentie tussen de API's stel ik voor deze werkwijze te volgen.

Dus queryparameter geslachtsnaam wordt dan naam__geslachtsnaam, geboortedatum wordt geboorte__geboortedatum, enz.

**Comment by JohanBoer** [comment]
Aangepast. In de pull-request die later vandaag wordt gemerged is dit verwerkt.
