### ISSUE TITLE
Als gemeente wil ik ingeschreven personen kunnen zoeken op het actuele verblijfsadres

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#9]
...zodat ik de gegevens van een persoon kan vinden.

**Acceptatiecriteria**
- [x] Het is mogelijk te kiezen om ook of juist geen overleden personen terug te krijgen
- [x] Het is mogelijk te zoeken (filteren) op de volgende eigenschappen van de persoon:
       * woonplaatsnaam
       * naamOpenbareRuimte
       * huisnummer
       * huisletter
       * huisnummertoevoeging
       * locatieaanduiding
- [x] Bij het zoeken/filteren op naamOpenbareRuimte mag een wildcard worden gebruikt  

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
dit wordt geïmplementeerd met het endpoint /actuelebewoners

**Comment by ArjanKloosterboer** [comment]
Zie [dit](https://github.com/VNG-Realisatie/BRK-Bevragingen/issues/7#issuecomment-421912150) en het daarop volgende comment m.b.t. de wijze van (specifieker) formuleren van de userstory's.

**Comment by JohanBoer** [comment]
Ik betwijfel of in deze endpoint de mogelijkheid om overleden personen te retourneren zin heeft. In principe is iemand van wie je weet dat hij overleden is geen actuele bewoner van het betreffende adres is. 
In de endpoint /VerblijfsplaatshistoriePersoon kan ik me dat wel voorstellen omdat je dan ook naar bewoner in het verleden wilt kijken.

**Comment by JohanBoer** [comment]
Uiteindelijk is dit in de endpoint /bewoningen gerealiseerd. Op dit endpoint kan je zowel actuele bewoners van een verblijfsplaats als de historische bewoners van een verblijfsplaats opvragen al dan niet inclusief overleden personen.

**Comment by JohanBoer** [comment]
Door de beslissing dat een verblijfsplaats een gegevensgroep van een ingeschreven persoon is kan deze bevraging op de ingeschreven persoon plaatsvinden,. Er zou in principe geen apart endpoint nodig zijn. Vooralsnog het endpoit /bewoningen wel in de openapi spec latane staan.

**Comment by JohanBoer** [comment]
Inmiddels is /bewoningen een historie endpoint. Het zoeken op actueel verplijfsadres is geïmplementeerd in /ingeschrevenpersonen
