### ISSUE TITLE
Als gebruiker van de API wil ik de attributen in het antwoord in een logische volgorde krijgen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#91]
...zodat ik het bericht goed kan lezen.

Dit issue is aangedragen door Maarten vd Broek.

De attributen die bovenaan moeten staan zijn m.n.
Naam
Geboortedatum
Verblijfplaats

**Comment by gertjanvanderkooij** [comment]
Hier voel ik in mee; aspect leesbaarheid. Binnen Operatie BRP ook wel mee gestoeid; volgorde blijft arbitrair en voor 'technisch betrokkenen' bleek het minder een issue. '_Parseren moet je toch!_'. 

Uiteindelijk wel voor gekozen en ingevuld. Als we hier verder mee gaan, kan ik oBRP-volgorde zoals indertijd afgestemd met stakeholders wel doorgeven.

**Comment by fsamwel** [comment]
Besproken in overleg 23 november.
* Volgorde maakt voor de developer niet uit, want attributen worden op naam opgehaald.
* Volgorde is, ook met api specificatie, niet af te dwingen en niet relevant. Attributen in een json object hebben per definitie geen vastgestelde volgorde. Zie http://json.org: "An object is an unordered set of name/value pairs"

Conclusie: beslissing: dit kunnen en gaan we nu niet doorvoeren.
