### ISSUE TITLE
Partnerschap, ouders en kinderen als endpoint voor nested resource

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#92]
Op dit moment zijn de relaties naar de partner, ouders en kinderen alleen beschikbaar wanneer deze embed worden via de expand parameter. Standaard worden deze dus niet teruggeleverd, ook niet als link in _links. Er kan op dit moment immers geen link worden opgenomen, omdat er geen endpoint is die dit kan leveren.

Maarten vd Broek heeft aangegeven dit niet handig te vinden.
Het is duidelijker en handiger en sluit beter aan bij wat men van REST verwacht om elke relatie ook in _links op te nemen en dus als resource ter beschikking te stellen.

**Comment by fsamwel** [comment]
Ik ben eigenlijk ook niet bij met de huidige modellering van deze relaties. Zie ook discussie in https://github.com/Geonovum/KP-APIs/issues/12

1. wanneer je niet expand/embed, blijkt nergens uit de "normale" resource dat er een partner, ouder of kind is. Maar dit zijn eigenlijk "normale" eigenschappen van de persoon (onderdeel van de PL van de persoon). 
2. dus de enige manier om te weten of iemand een partner heeft, is om de parameter expand te gebruiken
3. gebruik van de parameter expand is ingewikkeld. wanneer je niet alleen de relatie wilt weten, maar ook de gerelateerde persoon (bijv. de naam) die bijv. partner is, moet je expand=partnerschappen,partnerschappen.partners opgeven. dat is niet bepaald intuïtief of gebruikersvriendelijk
4. de relatie ouder bevat alleen de ouder_aanduiding (ouder1 of ouder2) plus geldigheidsdatums. ik vermoed dat de meeste gebruikers vooral de gegevens van de ouders interessant vinden, niet de ouder_aanduiding of geldigVan. idem voor de relatie kind

kunnen we deze relaties niet gewoon opnemen in de resource als gegevensgroep, zoals we ook gedaan hebben bij verblijfplaats, plus in _links de relaties naar betreffende personen? Met alleen de gegevens zoals die ook in categrieën 01/51, 02/52, 05/55 en 09/59 staan.
Dan sluit het misschien wat minder mooi aan bij een semantische modellering, maar past het wel beter bij de informatiebehoefte van de gebruikers.
Wanneer we dat doen kunnen we helemaal afscheid nemen van expand/embedden van relaties, want voor reisdocumenten lijkt me dat ook niet zo heel erg nodig. Zie #72.

**Comment by mvdbro** [comment]
Mijn idee was om binnen _links een relatie inclusief zijn gerelateerde beschikbaar te stellen, zodat je met één klik de gewenste gegevens kunt opvragen.

Platslaan binnen de resource zelf vind ik geen goed idee, omdat je dan default altijd alle relaties ophaalt. Voor de huidige GBAV is dit geen probleem, want die levert altijd de hele PL, maar voor toekomstige implementaties mogelijk wel.

Het gebruik van expand vind ik voldoende intuïtief en biedt een eenvoudige mogelijkheid om in één keer de hele PL op te halen inclusief al zijn relaties. Ik heb er wel voor gekozen om bij het specificeren van alleen een relatie alle gegevens van die relatie en zijn gerelateerde terug te geven. Het is dan niet nodig om ook nog te specificeren dat je gegevens van de gerelateerde wilt hebben.

Binnen expand zou ik ervoor kiezen om van de gerelateerde persoon alleen de gegevens op te nemen zoals die voorkomen op de PL van de persoon waarin de relatie ligt. 

Als je de resource voor de relatie opvraagt, dan zou je ervoor kunnen kiezen om de gerelateerde op te halen in de GBAV, zodat je over al zijn gegevens exclusief de relaties beschikt.

**Comment by CathyDingemanse** [comment]
> Ik ben eigenlijk ook niet bij met de huidige modellering van deze relaties. Zie ook discussie in [Geonovum/KP-APIs#12](https://github.com/Geonovum/KP-APIs/issues/12)
> 
> 1. wanneer je niet expand/embed, blijkt nergens uit de "normale" resource dat er een partner, ouder of kind is. Maar dit zijn eigenlijk "normale" eigenschappen van de persoon (onderdeel van de PL van de persoon).
> 2. dus de enige manier om te weten of iemand een partner heeft, is om de parameter expand te gebruiken

Dat is idd vreemd. Er moet een aanduiding komen in de INP resource dat er een ouder, kind of partnerrelatie is. Deze relatie moet bovendien herkenbaar zijn (over welke ouder of over welk kind of partner hebben we het?) Ik stel voor om de voornamen en geslachtsnaam van partners, ouders en kinderen op te nemen bij de INP resource.

> 3. gebruik van de parameter expand is ingewikkeld. wanneer je niet alleen de relatie wilt weten, maar ook de gerelateerde persoon (bijv. de naam) die bijv. partner is, moet je expand=partnerschappen,partnerschappen.partners opgeven. dat is niet bepaald intuïtief of gebruikersvriendelijk

Het is niet alleen gebruiksonvriendelijk, maar ook niet correct om de gegevens over de relatie, te weten:

- Datum   huwelijkssluiting/partnerschap
- Plaats   huwelijkssluiting/ partnerschap
- Land   huwelijkssluiting/ partnerschap
- Datum   ontbinding huwelijk/ partnerschap
- Plaats   ontbinding huwelijk/ partnerschap
- Land   ontbinding huwelijk/ partnerschap
- Reden   ontbinding huwelijk/ partnerschap
- Soort   verbintenis

als relatie-eigenschappen van de partner te beschouwen, en deze alleen te kunnen krijgen door de partner zelf op te vragen. Terwijl deze zaken ook op de INP van toepassing zijn. M.a.w. dit is info over de INP die ik ook moet kunnen raadplegen zonder de partner er bij te hoeven halen, en dat kan nu niet.
De andere gegevens op de PL in de categorie huwelijk (LO GBA) zijn eigenschappen van de partner.

Ik stel voor om de relatie-eigenschappen in de INP resource op te nemen, met een href naar de INP resource partner,  als de partner een INP is. Is dit wat jij ook voorstelt? 
Wat doen we dan als de partner een  ANP (niet ingeschreven persoon) is? Kunnen we van deze personen misschien sub-resources maken (ze bestaan immers niet zelfstandig, alleen in relatie tot de INP). De subresource is dan de inhoud van de rubriek partner op de PL van de INP m.u.v. de relatiegegevens die hierboven zijn genoemd.

Verder wil ik niet de persoon niet op te hoeven halen als ik alleen geinteresseerd ben in (een van) de partners:
/ingeschrevenpersonen/{burgerservicenummer}/partners
Met als resultaat van iedere partner de relatiegegevens met de INP, de naam van de partner en de href naar de INP/subresource partner

Bij een "expand=partner" zou je dan de INP plus de de INP of ANP (sub)resources van de partner binnenhalen.


> 4. de relatie ouder bevat alleen de ouder_aanduiding (ouder1 of ouder2) plus geldigheidsdatums. ik vermoed dat de meeste gebruikers vooral de gegevens van de ouders interessant vinden, niet de ouder_aanduiding of geldigVan. idem voor de relatie kind

Bij de ouder is alleen "datum ingang familierechtelijke betrekking" van toepassing op de relatie tussen de INP en de ouder. Alle andere gegevens uit de (LO GBA) categorie hebben betrekking op de ouder zelf. Voorstel is om deze samen met de voornamen en geslachtsnaam van de ouder op te nemen bij de INP resource, met een link naar INP resource van de ouder als de ouder een INP is of een subresource ANP als de ouder een ANP is. 
Bij een "expand=ouder" zou je dan de INP plus de de INP of ANP resources van de partner binnenhalen.

Met:
/ingeschrevenpersonen/{burgerservicenummer}/ouders
Met als resultaat van iedere ouder de datum ingang familierechtelijke betrekking, de voornamen en geslachtsnaam van de ouder en de href naar de INP/subresource partner

> 5. Embedded personen (kinderen, ouders, partners) betekent, wanneer deze personen niet ingeschreven zijn in de eigen gemeente, dat er meerdere vragen naar het GBA-V gaan. Dat zal GBA-V niet leuk vinden (was opmerking Maarden vd Broek).
> 
Tja, dat klopt, maar dat doe je niet zomaar. Er moet doelbinding zijn voor deze vragen. 

> kunnen we deze relaties niet gewoon opnemen in de resource als gegevensgroep, zoals we ook gedaan hebben bij verblijfplaats, plus in _links de relaties naar betreffende personen? Met alleen de gegevens zoals die ook in categrieën 01/51, 02/52, 05/55 en 09/59 staan.

Dat betekent dat je naast de relatie-eigenschappen ook veel eigenschappen van de gerelateerde persoon opneemt in de INP resource. Heeft als nadeel dat als ze in jouw autorisatie zitten, ze altijd worden meegeleverd, ookal heb je ze op dat moment niet nodig. Laat ik het zo zeggen: je hebt er op die manier geen invloed op als consumer.

> Dan sluit het misschien wat minder mooi aan bij een semantische modellering, maar past het wel beter bij de informatiebehoefte van de gebruikers.

> Wanneer we dat doen kunnen we helemaal afscheid nemen van expand/embedden van relaties, want voor reisdocumenten lijkt me dat ook niet zo heel erg nodig. Zie #72.

**Comment by fsamwel** [comment]
> Mijn idee was om binnen _links een relatie inclusief zijn gerelateerde beschikbaar te stellen, zodat je met één klik de gewenste gegevens kunt opvragen.
Bedoel je dat we een resource maken van de relatie inclusief gerelateerde?

> Binnen expand zou ik ervoor kiezen om van de gerelateerde persoon alleen de gegevens op te nemen zoals die voorkomen op de PL van de persoon waarin de relatie ligt.
Volgens mij neem je in embedded (met expand) hele resources op. Jeroen was daar eerder ook erg expliciet over, dat we resources niet voor een gedeelte mogen embedded.

> Ik stel voor om de relatie-eigenschappen in de INP resource op te nemen, met een href naar de INP resource partner, als de partner een INP is. @fsamwel: Is dit wat jij ook voorstelt?
Dat zou ook mijn voorstel zijn

> Wat doen we dan als de partner een ANP (niet ingeschreven persoon) is? Kunnen we van deze personen misschien sub-resources maken
Johan heeft dit nu al gemaakt in de api specificaties: /onderpersonen

> Platslaan binnen de resource zelf vind ik geen goed idee, omdat je dan default altijd alle relaties ophaalt. Voor de huidige GBAV is dit geen probleem, want die levert altijd de hele PL, maar voor toekomstige implementaties mogelijk wel.
> Voorstel is om deze samen met de voornamen en geslachtsnaam van de ouder op te nemen bij de INP resource, met een link naar INP resource van de ouder als de ouder een INP is of een subresource ANP als de ouder een ANP is.
Dit zijn tegengestelde meningen. Ik vermoed dat het voor performance niet/nauwelijks uitmaakt of je alleen voornamen en geslachtsnaam opneemt of de hele resource.

**Comment by mvdbro** [comment]
> > Mijn idee was om binnen _links een relatie inclusief zijn gerelateerde beschikbaar te stellen, zodat je met één klik de gewenste gegevens kunt opvragen.
> > Bedoel je dat we een resource maken van de relatie inclusief gerelateerde?

Inderdaad, een relatie zonder zijn gerelateerde is vanuit gebruiksoogpunt niet erg zinnig.
> 
> > Binnen expand zou ik ervoor kiezen om van de gerelateerde persoon alleen de gegevens op te nemen zoals die voorkomen op de PL van de persoon waarin de relatie ligt.
> > Volgens mij neem je in embedded (met expand) hele resources op. Jeroen was daar eerder ook erg expliciet over, dat we resources niet voor een gedeelte mogen embedded.

Het grote nadeel van die benadering is dat je dan voor alle gerelateerden separaat de PL moet lezen. Daarnaast vraag ik me af of je voor gerelateerden dezelfde autorisatie hebt als voor de persoon zelf.
> 
> > Ik stel voor om de relatie-eigenschappen in de INP resource op te nemen, met een href naar de INP resource partner, als de partner een INP is. @fsamwel: Is dit wat jij ook voorstelt?
> > Dat zou ook mijn voorstel zijn

Het lijkt mij beter om relaties te zien als aparte resources en via embed en expand desgewenst de relaties op te nemen in een respons.
> 
> > Wat doen we dan als de partner een ANP (niet ingeschreven persoon) is? Kunnen we van deze personen misschien sub-resources maken
> > Johan heeft dit nu al gemaakt in de api specificaties: /onderpersonen

Ik snap niet goed wat wordt bedoeld met subresources. De huidige modellering binnen embed is wat mij betreft ok.
> 
> > Platslaan binnen de resource zelf vind ik geen goed idee, omdat je dan default altijd alle relaties ophaalt. Voor de huidige GBAV is dit geen probleem, want die levert altijd de hele PL, maar voor toekomstige implementaties mogelijk wel.
> > Voorstel is om deze samen met de voornamen en geslachtsnaam van de ouder op te nemen bij de INP resource, met een link naar INP resource van de ouder als de ouder een INP is of een subresource ANP als de ouder een ANP is.

> > Dit zijn tegengestelde meningen. Ik vermoed dat het voor performance niet/nauwelijks uitmaakt of je alleen voornamen en geslachtsnaam opneemt of de hele resource.

Inderdaad, mijn keuze is om embedded de gegevens zoals op de PL voor de gerelatereerde staan op te nemen. In de als resource opgehaalde relatie zou ik ervoor kiezen om de gerelateerde wel separaat op te halen, zodat je dan de complete resource in de response krijgt.

**Comment by CathyDingemanse** [comment]
Ik realiseer mij dat mijn voorstel niet kan. Vanwege de doelbindingseis is het is niet mogelijk om voor het raadplegen van partner- op kindgegevens de hele resource persoon van de ouder/kind of partner op te halen. Daar is namelijk niet hetzelfde als het raadplegen van de ouder- kind of partnergegevens als onderdeel van de persoon. Mogelijkheden: 
of we nemen de relatiegegevens op met de gegevens van de gerelateerde 
of we maken een subresource van de gerelateerde (ouder, kind of partner is dan denk ik beter dan "onderpersoon"). In deze subresource nemen we dan een link op naar de INP.

**Comment by fsamwel** [comment]
Besproken in overleg 23 november.
Beslissing: 
* We definiëren sub-resources partnerschap, ouders en kinderen. Deze sub-resources bestaan uit de relatiegegevens plus beperkte eigenschappen van de partner (zoals die op de PL van de persoon staan in LO GBA). 
* In _links staan de links naar de subresources (dus niet naar de gerelateerde persoon).
* We definiëren endpoints voor deze subresources, bijv. /ingeschrevenpersonen/{burgerservicenummer}/ouders en /ingeschrevenpersonen/{burgerservicenummer}/ouders/{uuid}.
* In deze sub-resources zit een link naar de betreffende ingeschrevenpersoon wanneer dit een ingeschreven persoon is.
* Het is mogelijk deze sub-resources te embedded bij de persoon, zodat in één aanroep zowel de persoon als diens partner(schap), ouders en/of kinderen opgenomen kunnen worden.
* Partners zijn alleen actuele partners: geldigTotEnMet is altijd leeg (ex-partners worden via historie/.../partners opgevraagd)

**Comment by mvdbro** [comment]
Prima beslissing met nog één klein puntje.

Schrijft je met {uuid} in de derde bullet voor dat een relatie subresource altijd met een uuid moet worden gerepresenteerd of staat het de provider nog vrij om zelf te beslissen hoe een relatie wordt geïdentificeerd?

Het heeft mijn voorkeur om eventueel aanwezige sleutels van de provider te respecteren, omdat het voor de consumer niet relevant is hoe een relatie wordt geïdentificeerd. Als dit niet de bedoeling is, dan ben ik benieuwd naar de redenen om voor re schrijven dat uitsluitend met uuid’s resources mogen worden geïdentificeerd.

**Comment by fsamwel** [comment]
> Het heeft mijn voorkeur om eventueel aanwezige sleutels van de provider te respecteren,

De API strategie schrijft dit over ids van resources:

> Openbare identifiers
> Openbaar zichtbare identifiers (ID's), zoals die veelal in URI’s van RESTful API’s voorkomen, zouden onderliggende mechanismen (zoals een nummergenerator) niet bloot moeten leggen en zeker geen zakelijke betekenis moeten hebben.
> 
> UUID’s
> Het wordt aanbevolen om voor resources die een vertrouwelijk karakter hebben het concept van een UUID (Universally-Unique IDentifier) te gebruiken.

Hier houden we ons niet helemaal aan binnen de API, met name bij het gebruik van burgerservicenummer als identifier van een persoon. Maar dat is m.i. in het stelsel nodig (noodzakelijk), zodat vanuit bijv. BRK of HR verwezen kan worden naar een persoon in GBA/BRP. Deze registraties kennen alleen de functionele sleutel van personen (burgerservicenummer) en kunnen dus ook alleen deze gebruiken.
In het geval van de relaties partner/ouder/kind speelt dat niet, want daarnaar wordt alleen verwezen binnen deze API. Daarom is gekozen voor het gebruik van uuid.
Maar het argument om hier juist uuid te moeten gebruiken (zakelijke betekenis van de id) speelt hier ook niet.

**Comment by JohanBoer** [comment]
Dit is geïmplementeerd vanaf pull request #105

**Comment by fsamwel** [comment]
We hebben de suggestie van @mvdbro besproken om niet uuid, maar door provider te bepalen identificatie te definiëren voor de sub-resources partners, ouders en kinderen.

Dit nemen we over. Argument: registratie zou de UUID moeten vasthouden/bijhouden, maar kent die nu niet. Het is verantwoordelijkheid van de provider te zorgen dat een binnen de context unieke sleutel (in wordt geleverd waarmee het de sub-resource geïdentificeerd kan worden (dus de uri). Hoe maakt voor de gebruikers niet uit.

Bijvoorbeeld voor een ouder kan prima /ingeschrevenpersonen/555555021/ouders/1 worden gebruikt, of /ingeschrevenpersonen/555555021/ouders/1234ABC, enz.

Dus wordt het endpoint /ingeschrevenpersonen/{burgerservicenummer}/ouders/{sleutelbron}

In de definitie (description) van parameter sleutelbron wordt wel aangegeven dat bij voorkeur een uuid wordt gebruikt. Dat is immers het advies in de API strategie.

@JohanBoer verwerk jij dit in de API specs

**Comment by fsamwel** [comment]
> We hebben de suggestie van @mvdbro besproken om niet uuid, maar door provider te bepalen identificatie te definiëren voor de sub-resources partners, ouders en kinderen.
> 
> Dit nemen we over. Argument: registratie zou de UUID moeten vasthouden/bijhouden, maar kent die nu niet. Het is verantwoordelijkheid van de provider te zorgen dat een binnen de context unieke sleutel (in wordt geleverd waarmee het de sub-resource geïdentificeerd kan worden (dus de uri). Hoe maakt voor de gebruikers niet uit.
> 
> Bijvoorbeeld voor een ouder kan prima /ingeschrevenpersonen/555555021/ouders/1 worden gebruikt, of /ingeschrevenpersonen/555555021/ouders/1234ABC, enz.
> 
> Dus wordt het endpoint /ingeschrevenpersonen/{burgerservicenummer}/ouders/{sleutelbron}
> 
> In de definitie (description) van parameter sleutelbron wordt wel aangegeven dat bij voorkeur een uuid wordt gebruikt. Dat is immers het advies in de API strategie.
> 
> @JohanBoer verwerk jij dit in de API specs

@JohanBoer dit is nog niet verwerkt in de specs, want daarin staan nog de UUID's. Die zijn echter niet te implementeren. Kan dit worden aangepast?
