### ISSUE TITLE
Bij referentielijst waarde is omschrijving voldoende

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#93]
gemeld door Maarten vd Broek: 
Voor een referentielijst-attribuut (tabel--entiteit), bijvoorbeeld nationaliteit, is het teruggeven van de code niet nodig. Eigenlijk is er alleen behoefte aan de omschrijving, niet aan de code.
Dit maakt het antwoordbericht eenvoudiger en overzichtelijker (platter).

**Comment by mvdbro** [comment]
Mijn standpunt is inmiddels wat gewijzigd. Voor de GBA-tabellen lijkt het mij goed om in de API zowel de code als de omschrijving op te nemen, omdat iedereen nu beschikt over de code en daar functionaliteit voor heeft. Voor elementen waar nu de omschrijving wordt gebruikt zie ik geen aanleiding om hier ook een code toe te voegen, bijv. VoorvoegselGeslachtsnaam.

**Comment by CathyDingemanse** [comment]
Als deze API gebruikt wordt voor het raadplegen van een resource waarmee lokale kopieen van gegevens actueel worden gehouden, dan zullen we de code moeten leveren.

**Comment by fsamwel** [comment]
Gezien laatste twee opmerkingen zijn we in overleg 23 november tot beslissing te komen dit issue te sluiten. 
Ontwerpbeslissing "[Dynamische domeinwaarden worden in de response opgenomen met zowel de code als de omschrijving](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#dynamische-domeinwaarden-worden-in-de-response-opgenomen-met-zowel-de-code-als-de-omschrijving)" blijft dus gehandhaafd.

**Comment by mvdbro** [comment]
De specificatie neemt nu voor enumeraties de code op in de resource en niet de omschrijving. Het is daarmee de verantwoordelijkheid van de consumer om de codes te vertalen naar de omschrijvingen. De codeing voor indicatie geheim zullen veel gevruikers bijv. niet veel zeggen.

Is het niet beter om alleen de omschrijvingen op te nemen of zowel de code als de omschrijving?

**Comment by CathyDingemanse** [comment]
Dat laatste is de bedoeling. Ik denk dat dit work in progress is. Op welke plekken ben je dit tegen gekomen?

**Comment by fsamwel** [comment]
Er wordt een onderscheid gemaakt tussen enumeraties en "dynamische domeinwaarden" oftewel de GBA tabellen.
Enumeraties zijn vast gedefinieerd in de API specificatie, waarbij in de description de omschrijving is opgenomen. Overweging hiervoor is dat er enumeraties zijn met zeer lange omschrijving-waarden. Ook zijn de omschrijvingen lang niet altijd geschikt om te communiceren met de gebruiker, dus de consumer moet toch een vertaling maken naar een gebruikersvriendelijke omschrijving.
De dynamische waarden (tabellen) kunnen veranderen. Daarbij nemen we zowel code als omschrijving op, omdat we niet zeker zijn dat provider en consumer altijd dezelfde versie van de tabellen heeft én omdat voor veel gebruik de omschrijving relevant is.

**Comment by mvdbro** [comment]
> Dat laatste is de bedoeling. Ik denk dat dit work in progress is. Op welke plekken ben je dit tegen gekomen?

In alle types voor enumeraties.

@CathyDingemanse en @fsamwel lijken het niet eens. Ik laat het aan jullie over om tot een beslissing te komen.

**Comment by CathyDingemanse** [comment]
> Dat laatste is de bedoeling. Ik denk dat dit work in progress is. Op welke plekken ben je dit tegen gekomen?

Sorry, onjuist!
