### ISSUE TITLE
Als gebruiker van de api wil ik kunnen zien of een lege waarde bekend leeg is óf onbekend

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#94]
gemeld door Maarten vd Broek

Onderscheid niet bekend en bekend leeg is nodig, ook bij datums (zoals overlijdensdatum). Voorstel om onderscheid te maken tussen lege waarde "", te interpreteren als leeg, en afwezig (attribuut zit niet in het antwoord) of null, te interpreteren als waarde is onbekend. 

Dit is m.n. relevant voor situatie dat API geleverd wordt door gegevensmagazijn, en die weet niet altijd alle gegevens. Bijvoorbeeld wanneer een persoon in het gegevensmagazijn uit het BRK of HR komt.

In het geval van een gegevensgroep die meerdere keren voor kan komen, bijvoorbeeld verblijfstitel, is dit ook relevant. Als het attribuut (de groep) niet voorkomt is het niet bekend, als het voorkomt als nationaliteit: [] (lege array) is er geen nationaliteit (persoon is statenloos).

**Comment by fsamwel** [comment]
Als het probleem is dat de bron gevuld is uit een niet authentieke bron, moet je je m.i. ook afvragen of de api dit wel moet teruggeven. De gebruiker moet er toch op kunnen vertrouwen dat het antwoord juist is?
Bijvoorbeeld als je een persoon opvraagt die uit het HR blijkt te komen, krijg je wel een verblijfplaats terug, maar dat hoeft helemaal niet de actuele verblijfplaats te zijn die teruggegeven wordt, maar de client kan dit vervolgens wel gebruiken om bijvoorbeeld een brief te sturen.
Wellicht moeten we specificeren dat de api alleen personen terug mag geven die afkomstig zijn uit GBA of RNI?

**Comment by dennisdewit81** [comment]
Ik zou zo lang mogelijk wegblijven van het 'geenWaarde' vs. 'waardeOnbekend' onderscheid. Hoe veel uren daar aan leverancierskant in het verleden wel over gediscussieerd is omdat ontwikkelaars het onderscheid niet begrepen (en niet begrijpen)... Als we API's maken die lekker handig zijn voor developers moeten we het ook eenvoudig houden.

Over de opmerking "Dit is m.n. relevant voor situatie dat API geleverd wordt door gegevensmagazijn, en die weet niet altijd alle gegevens" het volgende: We maken de API's uiteindelijk voor het bevragen van de bron (BRP) en niet voor het bevragen van een duplicaat zoals het gegevensmagazijn. Dus in mijn ogen speelt 'het niet weten' in de doelsituatie niet.

**Comment by JohnRooijakkers** [comment]
Ik snap je punt Dennis, maar volgens mij kunnen we hier niet lang van wegblijven.
Hetzelfde geldt voor onvolledige datums die in de GBA voorkomen.

Daarnaast vind ik dat er veel naar het belang en gemak van de ontwikkelaar wordt gekeken. Uiteindelijk gaat het m.i. om de toegevoegde waarde voor de business. Maar dit is een geheel andere discussie en zal ik hier niet verder voeren.

**Comment by CathyDingemanse** [comment]
> Ik zou zo lang mogelijk wegblijven van het 'geenWaarde' vs. 'waardeOnbekend' onderscheid. Hoe veel uren daar aan leverancierskant in het verleden wel over gediscussieerd is omdat ontwikkelaars het onderscheid niet begrepen (en niet begrijpen)... Als we API's maken die lekker handig zijn voor developers moeten we het ook eenvoudig houden.
> 
Hear! Hear!

**Comment by mvdbro** [comment]
Ik snap het argument van het probleem voor de ontwikkelaar niet zo goed. Zoals het er nu naar uitziet worden de beoogde API’s ontwikkeld met als provider de basisregistratie. Deze ene partij moet in staat zijn om het omderscheid tussen onbekend en geen waarde te begrijpen. Voor de consumers lijkt het me ook niet erg ingewikkeld. Dat bijnhet ontbreken van een element de waarde onbekend is, lijkt mij heel intuïtief net zoals dat een lege waarde betekent dat er geen waarde is.

Het grote voordeel van deze benadering is dat je een uniform mechanisme hebt om dit onserscheid te communiceren en je je niet per element hoeft af te vragen of het ontbreken van een waarde betekent dat er geen waarde is of dat de waarde onbekend is.

Het belang hiervan wordt nog groter op het moment dat autorisatie nodig is. Het is toch niet de bedoeling dat het niet geautoriseerd zijn voor een element leidt tot de conclusie dat het element geen waarde heeft, omdat dit de normale interpretatie is voor het ontbreken van een element. De juiste interpretatie is dan dat voor jou de waarde onbekend is, wat precies overeenkomt met het ontbreken in de respons. Het gaat wel erg ver als je als consumer je autorisatie moet kennen om de respons correct te kunnen interpreteren.

**Comment by fsamwel** [comment]
Besproken in overleg 23 november. Besloten dit onderscheid tussen leeg en onbekend niet in de api te maken.
Overwegingen:
* api zo eenvoudig mogelijk houden
* we kennen geen businessvraag waarin we dit willen weten
* speelt niet bij een authentieke bron

Dit betekent m.i. ook dat wanneer de api door een gegevensmagazijn wordt geleverd (zolang er geen authentieke bron is die de api kan leveren), dit gegevens magazijn moet zorgen dat deze alleen authentieke gegevens levert. En wanneer het de authentieke gegevens zelf niet heeft deze ophaalt bij de authentieke bron (locale GBA of GBA-V)
