### ISSUE TITLE
Als gebruiker van de api wil ik zoekresultaten gesorteerd terugkrijgen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#95]
...zodat ik het gewenste resultaat makkelijker kan vinden in de lijst.

verzoek van Maarten vd Broek

De api strategie biedt hiervoor de parameter sort. Maar dit kan zware belasting zijn voor provider, en dus performance issue, omdat niet vooraf afgebakend is op welke combinatie van attributen gesorteerd wordt.

Alternatief is een vaste sortering af te spreken in de api, eventueel verschillend per zoekpad.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by dennisdewit81** [comment]
Sortering is wellicht handig voor de consumer, maar laten we eens kijken wat er gebeurt als we het gewoon niet ondersteunen. Consumers lossen dit dan zelf waarschijnlijk op/of het blijkt helemaal niet zo'n issue te zijn voor consumers. 

Wat mij betreft is dit typisch iets dat nu besproken wordt omdat het in StUF wel zit (en we dus nu het idee hebben dat we er iets mee moeten), we zijn hier echter niet per definitie StUF aan het vervangen. Neem wat mij betreft hier wat rigoureuzer keuzes en ondersteun het dus niet. Als over een jaar blijkt dat we het echt missen dan kun je het alsnog overwegen.

**Comment by CathyDingemanse** [comment]
Ben het helemaal eens met Dennis. 
Ten eerste kunnen wij niet voor alle consumers vooraf verzinnen waarop moet worden gesorteerd. Wat is dan de waarde van server side sorteren? 
Ten tweede wordt e.e.a. meestel zelf wel gepresenteerd door de tool in het inleest.
Ten derde is er geen concrete businessvraag van een afnemer, die opwegen tegen de nadelen t.a.v. performance.

**Comment by JohnRooijakkers** [comment]
Uiteraard moeten we niet klakkeloos StUF vervangen, maar het is wellicht wel handig om te weten waarom het destijds in StUF is opgenomen. Voor zover ik me kan herinneren, heeft dit te maken met het kunnen stellen van vervolgvragen als de initiële vraag teveel treffers oplevert om ineens terug te leveren. Als die situatie niet optreedt, lijkt de destijds geïntroduceerde oplossing uiteraard ook niet van belang.

**Comment by mvdbro** [comment]
Ik wil hierin StUF niet volgen, want dat biedt de mogelijkheid om een sortering te specificeren. Mijn voorstel is om de consumer niet de mogelijkheid te geven om een sortering te specificeren, conform de reactie van Dennis en Cathy. 

Mijn voorstel is tevens om afhankelijk van de gebruikte zoekparameters aan de provider wel een sortering voor te schrijven, zodat de consumer in geval van meerdere resultaten de volgorde een beetje logisch vindt. Bij een selectie op geboortedatum c.q. postcode + huisnummer ligt het bijvoorbeeld voor de hand te sorteren op naam resp. op huisletter, huisnummertoevoeging en naam.

**Comment by gertjanvanderkooij** [comment]
Vaste sortering op basis van gehanteerd zoekpad lijkt me inderdaad goed om af te spreken.  

Zoals bv. ook een vaste sortering bij het doorgeven van de detailgegevens. Bv. igv adreshistorie de actuele als eerste in de rij; vervolgens in aflopende volgorde de historische voorkomens. Idem voor huwelijken/partnerschappen. Voor Kinderen bv. eerstgeborene eerst etc. Dit ook zo op te nemen in de specs voor de service-implemantie door de provider.

**Comment by fsamwel** [comment]
besproken in overleg 23 november. Beslissing:
* Bij historie wordt aflopend gesorteerd op geldigVan, zodat de meest actuele bovenaan staat. In het geval van historie/bewoningen worden de gevonden adressen niet gesorteerd, maar worden de bewoners wel gesorteerd op geldigVan.
* Overige zoekvragen/collections: geen sortering.

Ratio:
* vrije sortering vanuit gebruiker (sort parameter) kan zware belasting voor provider zijn
* standaard sortering is niet te bepalen, gewenste sortering hangt af van het gebruik
* door de client is gemakkelijk zelf de gewenste sortering in de resultaten aan te brengen

**Comment by gertjanvanderkooij** [comment]
Ik zou de sorteeralgoritme die gehanteerd werd bij oBRP nog even doorgeven. Vanwege de vastlegging van FormeleHistorie was deze wat uitgebreider. Dat deel heb ik er voor nu even buiten gelaten.

Sorteervolgorde 'Materiële Historie - Meest recente vooraan' als volgt:
1) Datum einde geldigheid aflopend
2) Datum aanvang geldigheid aflopend

**NB.** Werkt voor 'stapels' die elkaar niet mogen overlappen (bv. partnerschappen, adressen) en stapeld die elkaar wel mogen overlappen (in oBRP bv. Nationaliteit).

Voorafgaand aan de sortering volgende regels:
- Indien Datum einde geldigheid niet gevuld, de waarde '99999999' hanteren
- Voor (deels) onbekende datums de datum aanvullen met '00' voor de onbekende delen (dd, mm, jjjj).
