### ISSUE TITLE
Naam en naamgebruik samenvoegen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#96]
op dit moment heeft de resource ingeschrevenpersonen een gegevensgroep "naam" en een gegevensgroep "naamgebruik".

Dat is voor de gebruiker niet logisch. Wanneer ik bijvoorbeeld de aanschrijfwijze zou willen weten, zou ik die in de groep "naam" denken te kunnen vinden.

Voorstel is de attributen uit "naamgebruik" samen te voegen in groep "naam".

**Comment by CathyDingemanse** [comment]
Nu staat aanschrijfwijze in "naamgebruik", samen met aanduiding naamgebruik. In de "naam" staan geslachtsnaam, voornamen, voorvoegsel, adellijke titel predikaat. Samenvoegen lijkt een prima idee!

**Comment by fsamwel** [comment]
Besloten (23 november) naam en naamgebruik samen te voegen in één groep "naam".
@JohanBoer: voer jij dit door in de api specificaties

**Comment by JohanBoer** [comment]
Doorgevoerd vanaf pullrequest #105
