### ISSUE TITLE
Geboorteplaats, geboorteland, plaatsOverlijden en landOverlijden uit resource verwijderen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#97]
Opmerking/verzoek van Maarten vd Broek:

Geboorteplaats, geboorteland, plaatsOverlijden en landOverlijden: niemand heeft behoefte aan deze gegevens. Kunnen eruit.

Voordeel is dat geboorte en overlijden dan geen gegevensgroep meer zijn, maar een normaal attribuut met een waarde.
Nu moet je namelijk, ook als gevolg van de mogelijk onvolledige datum, de geboortedatum ophalen uit geboorte > geboortedatum > datum
En heet de parameter om op geboortedatum te zoeken geboorte__geboortedatum

**Comment by gertjanvanderkooij** [comment]
> niemand heeft behoefte aan deze gegevens

Nogal cru gesteld ... volgens mij wel degelijk behoefte aan deze gegevens.

**Comment by CathyDingemanse** [comment]
> > niemand heeft behoefte aan deze gegevens
> 
> Nogal cru gesteld ... volgens mij wel degelijk behoefte aan deze gegevens.

Zeer eens met Gert-Jan. Kan Maarten deze uitspraak staven met een grondige inventarisatie van de businessbehoefte? Zie de autorisatieprofielen van Den Haag.

**Comment by mvdbro** [comment]
@CathyDingemanse  en @gertjanvanderkooij 

Het feit dat ik de businessbehoefte niet kan staven was aanleiding voor mijn opmerking. Zouden jullie concrete voorbeelden kunnen geven van taken buiten burgerzaken waarvoor deze gegevens van belang zijn?

**Comment by gertjanvanderkooij** [comment]
Zie bijgaand autorisatiebesluit. Opsomming taken vanaf blz. 14. Volgens bijgevoegd autorisatiebesluit bv. dus voor Jeugd-, Drank- en horreca-, RMC- en Opsporing-taak. Ik zou gebruik ook verwachten in Weerk- en Inkomen en Welzijn-hoek, maar hier beperkt tot geboortedatum of niet alle taken genoemd? WMO? 

In de praktijk wellicht anders; dit laat ik even aan @CathyDingemanse.
[510001 Gemeente Rotterdam BRP 1-7-2018.pdf](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2605390/510001.Gemeente.Rotterdam.BRP.1-7-2018.pdf)

**Comment by fsamwel** [comment]
beslissing 23 november: gegevens zijn dus toch nodig (zie opmerking Gert Jan)
