### ISSUE TITLE
Ingeschreven persoon en ander persoon hebben andere naam voor geboortedatum/datumgeboorte en onderlijdernsdatum/datumoverlijden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Bevragingen-ingeschreven-personen#98]
Melding van Maarten vd Broek:

Ingeschreven persoon en ander persoon hebben andere naam voor geboortedatum/datumgeboorte en onderlijdernsdatum/datumoverlijden

ingeschrevenpersonen
* geboorte.geboortedatum
* overlijden. datumOverlijden

anderpersonen
* geboortedatum (in pull request #89 wordt het datumGeboorte voor de anderpersonen)
* overlijdensdatum

Een consequente naamgeving zou duidelijker zijn, dus zoveel mogelijk gelijke naamgeving voor ingeschreven personen en niet-ingeschreven (ander) personen. In LO GBA wordt er volgens mij ook geen onderscheid gemaakt hiertussen. Zowel de persoon, als de partner, ouder en kind gebruiken dezelfde groep 03 voor geboorte.

In LO GBA is het voor geboorte "geboortedatum" en voor overlijden "Datum overlijden".

**Comment by gertjanvanderkooij** [comment]
Yep; zie ook opmerkingen over naamgeving in mijn eerder doorgestuurde spreadsheet!

**Comment by fsamwel** [comment]
is inmiddels gecorrigeerd in de api specificaties
