### ISSUE TITLE
Scope van Bevragingen-ingeschreven-personen

### ISSUE THREAD

**Issue by mvdbro** [VNG-Realisatie/Bevragingen-ingeschreven-personen#99]
**Achtergrond**
Ik heb als doelstelling van Common Ground tot voor kort primair gezien het overbodig van datadistributie en het rondpompen van gegevens in gemeenten naar allerlei taakspecifieke applicaties. De presentatie van De gemeente Den Haag op de leveranciersdag van VNG Realisatie in november bracht een andere doelstelling in beeld: het als gemeenten volledig delegeren van het ontsluiten van gegevens uit het stelsel van basisregistraties aan voorzieningen geleverd door de rijksoverheid.

**Probleemstelling**
De requirements voor de API zijn niet hetzelfde voor beide doelstellingen. Bij het ontsluiten van gegevens ten behoeve van taakspecifieke applicaties staan de behoeften van deze applicaties centraal. Deze behoeften zijn binnen de Gemma architectuur gemodelleerd in RSGB2 en RSGB3 en worden op dit moment binnengemeentelijk ondersteund met behulp van gegevensmagazijnen (RSGB2) en StUF vraag/antwoord.

Bij het volledig delegeren van de ontsluiting van de basisregistraties naar de rijksoverheid staat het stelsel van basisregistraties centraal en niet de behoeften van de gemeentelijke taakspecifieke applicaties. Je krijgt dan een qua scope van de gegevens aanbodgedreven API. Er zal moeten worden nagegaan of deze in voldoende mate voldoet aan de businessbehoeften van de consumers.

**Voorstel**
Mijn voorstel is om in eerste instantie uit te gaan van de requirements van de taakspecifieke applicaties binnen gemeenten. Dit leidt dan tot een API die geïmplementeerd kan worden als een converter die onderliggend gebruik maakt van StUF vraag/antwoord op gegevensmagazijnen of van aanroepen van de nu geboden webservices van de basisregistraties (GBAV voor buitengemeentelijke personen, HR Dataservice, en dergelijke). Een dergelijke converter kan vrij snel na het gedefinieerd zijn van de API beschikbaar komen en kan dan geïmplementeerd worden in alle gemeenten die beschikken over een gegevensmagazijn met StUF vraag/antwoord. Het gegevensmagazijn is noodzakelijk, omdat de GBAV het opvragen van binnengemeentelijke personen verbiedt en de huidige GBA applicaties geen webservices voor het ophalen van gegevens bieden. Het gegevensmagazijn heeft daaarnaast als voordeel dat voor personen, adressen en gebouwen niet alleen de basisregistratiegegevens worden ondersteund, maar het RSGB. De vruchten van de architectuurprincipes van Common Ground worden zo al snel geplukt en er kan vanaf 2019 een begin worden gemaakt met het afbouwen van het rondpompen van gegevens in gemeenten.

Tegelijkertijd of onmiddellijk na vaststelling van deze API kan een tweede API ontwikkeld worden voor de ontsluiting ten behoeve van gemeenten van het stelsel van basisregistraties. Zeker voor de persoonsgegevens zal de implementatie van deze API vermoedelijk nog geruime tijd op zich laten wachten. Bij de introductie van deze tweede API verandert er voor de taakspecifieke applicaties niets, want zij blijven gebruik maken van de eerste API. De provider van de eerste API roept in de achtergrond de basisregistratie API aan en andere API’s voor gegevens die de basisregistraties niet leveren.

**Comment by mvdbro** [comment]
Ik weet niet waar dit verbod precies is geformuleerd. Ik heb het ooit ergens opgepikt en het lijkt me goed om dit te verifiëren bij de GBAV. Ik snap wel dat de GBAV op dit moment niet de capaciteit heeft om bij iedere vraag naar een persoon vanuit een gemeente binnen redelijke responstijden te antwoorden. In de toekomst wordt dit ongetwijfeld wel mogelijk.

**Comment by gertjanvanderkooij** [comment]
Hierop is geen verbod.

> omdat de GBAV het opvragen van binnengemeentelijke personen verbiedt

Hierop rust geen verbod. Er is een periode geweest waarin men vanuit RvIG terughoudendheid in het gebruik vroeg als personen ook in de lokale GBA aanwezig zijn. Speelt volgens mij niet meer.

**Comment by mvdbro** [comment]
De conclusie is daarmee dat het gegevensmagazijn alleen noodzakelijk is, als je meer gegevens wilt ontsluiten dan de basisregistraties bieden. Een mogelijke andere reden om voor personen niet niet voor de GBAV te kiezen kan de kosten zijn. Je betaalt bij T&T per opgevraagde persoon. Ik weet niet precies wat de kosten worden, maar het lijkt me goed om dit in kaart te brengen.

**Comment by mvdbro** [comment]
De door Gertjan in issue 97 aangereikte link 
https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2605390/510001.Gemeente.Rotterdam.BRP.1-7-2018.pdf voor het autorisatiebesluit van de gemeente Rotterdam geeft overigens op pagina 97 bovenaan expliciet geen autorisatie voor het ophalen van gegevens van eigen ingeschrevenen in de GBAV. Op welke plaats wordt dit overruled of is het ophalen van eigen ingeschrevenen toch formeel niet toegestaan?

**Comment by gertjanvanderkooij** [comment]
Autorisatiebesluit was ter illustratie meegestuurd. Voor gemeenten zijn meer autorisatiebesluiten van toepassing; bijgaand ander voorbeeld waarbij beperking niet is opgenomen: 
[412601 Autorisatiebesluit GSD BKWI 01-09-2018.pdf](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2606925/412601.Autorisatiebesluit.GSD.BKWI.01-09-2018.pdf)

**Comment by fsamwel** [comment]
@arnoudquanjer dit is denk ik vooral een architectuurvraag:
- hoe gaan we om met gemeentelijke kerngegevens, wat is de bron daarvan en komt daar een API voor
- hoe gaan we om met samengestelde API, waarin GBA gegevens van een persoon en gemeentelijke kerngegevens van een persoon (zoals correspondentieadres, e-mailadres) samen geleverd kunnen worden aan een client
- hoe gaan we om met (afwezigheid van) actuele bijhouding van gegevens. Bijvoorbeeld wanneer een kadastrale zaak (BRK) of een bedrijf (HR) een eigenaar heeft die geen ingeschreven persoon is. Kadaster en KvK houden het actuele adres van de eigenaar niet bij. Hoe kan de gemeente een brief naar het juiste actuele adres sturen. En dus hoe gaat de API het actuele en juiste adres teruggeven. Schijnbaar houden sommige gemeenten een eigen registratie daarvan bij.

**Comment by JohanBoer** [comment]
> * hoe gaan we om met gemeentelijke kerngegevens, wat is de bron daarvan en komt daar een API voor
Buiten scope

> * hoe gaan we om met samengestelde API, waarin GBA gegevens van een persoon en gemeentelijke kerngegevens van een persoon (zoals correspondentieadres, e-mailadres) samen geleverd kunnen worden aan een client
Buiten scope

> * hoe gaan we om met (afwezigheid van) actuele bijhouding van gegevens. Bijvoorbeeld wanneer een kadastrale zaak (BRK) of een bedrijf (HR) een eigenaar heeft die geen ingeschreven persoon is. Kadaster en KvK houden het actuele adres van de eigenaar niet bij. Hoe kan de gemeente een brief naar het juiste actuele adres sturen. En dus hoe gaat de API het actuele en juiste adres teruggeven. Schijnbaar houden sommige gemeenten een eigen registratie daarvan bij.
Buiten scope
